import React, { createContext, useContext, useState, useEffect } from 'react';
import { SupportedLanguage } from '@studentlife/shared';

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Nav & System
    app_subtitle: 'Operating System for Study, Exams & Career',
    cockpit: 'Cockpit',
    academics: 'Academics 📚',
    academics_full: 'Academics & Exams',
    ai_copilot: 'AI Copilot 🤖',
    ai_copilot_full: 'AI Study & Smart Tools',
    career: 'Career & Gigs 💼',
    career_full: 'Career & Opportunities',
    labs: 'Research & Labs 🔬',
    labs_full: 'DeepTech & STEM Labs',
    community: 'Campus Hub 👥',
    community_full: 'Campus Community & Arena',
    campus: 'Campus & Health 🏫',
    campus_full: 'Campus Life & Wellness',
    grandmaster: 'Grandmaster 👑',
    roadmap: 'Roadmap 🗺️',
    search: 'Search',
    api_online: 'ONLINE',
    api_standby: 'STANDBY',
    daily_digest: 'Daily Digest ☀️',
    sign_in: 'Sign In / Sign Up',
    sign_out: 'Sign Out',

    // Dashboard & Student Card
    level_scholar: 'LEVEL {level} SCHOLAR',
    total_xp: 'Total XP',
    xp_needed: 'XP needed',
    day_streak: 'Day Streak',
    edit_profile: 'Edit Profile',
    daily_study_target: 'Daily Study Target',
    target_exams: 'Target Exams',
    dream_career: 'Dream Career',
    skills: 'Skills',

    // Focus & Progress
    smart_focus_engine: 'Smart Focus Engine',
    pomodoro_protocol: 'Pomodoro Deep Work Protocol',
    focus_25: '25m Focus',
    focus_50: '50m Deep',
    break_5: '5m Break',
    study_commitment: "Today's Study Commitment",
    daily_telemetry: 'Daily target telemetry',
    time_studied_today: 'Time Studied Today',
    target_label: 'Target',
    remaining_label: 'Remaining',

    // Exams & Revision
    target_exam_countdowns: 'Target Exam Countdowns',
    milestone_tracker: 'Milestone countdown tracker',
    view_prep_hub: 'View Prep Hub',
    days_left: 'days remaining',
    spaced_repetition_queue: 'Spaced Repetition Due (SM-2)',
    memory_curve: 'Active recall memory retention curve',
    start_rapid_review: 'Start Rapid Review',
    due_today: 'cards due for active recall today',
    estimated_time: 'Est. completion time',

    // AI Accelerators
    ai_shortcuts_title: 'AI Study & Mentor Shortcuts',
    ai_shortcuts_sub: 'Instant context-aware acceleration tools',
    summarize_notes: 'Summarize Notes',
    generate_flashcards: 'Generate Flashcards',
    ask_ai_mentor: 'Ask AI Mentor',
    quote_text: '"Small daily disciplines repeated with consistency lead to monumental achievements over time."',
    quote_author: '— Robin Sharma',

    // Live Telemetry & Footer
    live_telemetry: 'Live Telemetry',
    streaming: 'STREAMING',
    paused: 'PAUSED',
    footer_text: 'StudentLife OS 16.0 (Century Grandmaster Edition) • 100/100 Phases Fully Operational • 100% Production Ready 🏆💯',

    // Tool Ribbon Names
    tool_PLANNER: 'Planner 📅',
    tool_SYLLABUS: 'Syllabus 🌲',
    tool_NOTES: 'Notes Hub 📝',
    tool_REVISION: 'SM-2 Revision 🧠',
    tool_EXAM_PREP: 'Exam Prep 🎯',
    tool_QUESTION_BANK: 'PYQ Bank 📚',
    tool_MOCK_TEST: 'Mock Tests ⏱️',
    tool_CUSTOM_PAPER: 'Paper Synthesizer 📜',
    tool_RANK_PREDICTOR: 'AIR Predictor 🎯',
    tool_EXAM_TREND: 'Exam Trends 🔮',
    tool_ANKI_FSRS: 'Anki FSRS Sync 🔄',
    tool_ACADEMIC_INTEGRITY: 'Academic Integrity 🛡️',
    tool_ANALYTICS: 'Analytics 📈',
    tool_AI_STUDY: 'AI Study Assistant 🤖',
    tool_AI_MENTOR: 'AI Mentor 360° 🎓',
    tool_VOICE_TUTOR: 'Voice Tutor 🎙️',
    tool_AI_PODCAST: 'AI Podcast 🎙️',
    tool_SOCRATIC_DEBATE: 'Socratic Debate ⚖️',
    tool_CONCEPT_GRAPH: 'Mind Map Graph 🕸️',
    tool_AI_WHITEBOARD: 'AI Whiteboard 🎨',
    tool_DOCUMENT_ANNOTATOR: 'PDF Annotator 📝',
    tool_OCR_SCANNER: 'OCR Scanner 📷',
    tool_VIDEO_NAVIGATOR: 'Video Navigator 🎬',
    tool_SPEED_READER: 'Speed Reader ⚡',
    tool_POLYGLOT_TRANSLATOR: 'Polyglot Translator 🌐',
    tool_SLIDE_GENERATOR: 'Slide Studio 📊',
    tool_CAREER: 'Career Intel 💼',
    tool_RESUME: 'Resume & ATS 📄',
    tool_INTERNSHIPS: 'Internships 🎯',
    tool_SCHOLARSHIPS: 'Scholarships 🏆',
    tool_MOCK_INTERVIEW: 'Viva & Interview 🎙️',
    tool_STUDENT_FINANCES: 'Finances & Gigs 💳',
    tool_MICRO_INTERNSHIP: 'Micro-Gigs Escrow 💼',
    tool_CAMPUS_INCUBATOR: 'Startup Incubator 🚀',
    tool_FELLOWSHIP_DRAFTER: 'Fellowship Drafter 🏅',
    tool_SKILL_PASSPORT: 'Skill Passport 🎖️',
    tool_VENTURE_SAFE: 'Venture SAFE 💼',
    tool_HFT_ORDERBOOK: 'HFT Order Book 📈',
    tool_RESEARCH_LAB: 'AI Research Lab 🧬',
    tool_ARXIV_SCHOLAR: 'arXiv Scholar 📄',
    tool_CODE_SANDBOX: 'Code Sandbox 💻',
    tool_LATEX_STUDIO: 'LaTeX Studio 📐',
    tool_PATENT_DRAFTER: 'Patent & IP 📜',
    tool_HOLO_SIMULATIONS: '3D Holo-Lab 🧬',
    tool_QUANTUM_LAB: 'Quantum Lab ⚛️',
    tool_QUANTUM_QKD: 'Quantum QKD 🔑',
    tool_LAB_NOTEBOOK: 'Lab Notebook 🧪',
    tool_KERNEL_PROFILER: 'SIMD Profiler ⚡',
    tool_ASTRODYNAMICS: 'Astrodynamics 🪐',
    tool_CHEMICAL_RETRO: 'Retrosynthesis 🧪',
    tool_SCHOLAR_TRACKER: 'Scholar Tracker 🎓',
    tool_NEUROMORPHIC_SNN: 'Neuromorphic SNN 🧠',
    tool_PAPER_REFEREE: 'Peer Reviewer 📝',
    tool_CRISPR_EDITOR: 'CRISPR Gene Editor 🧬',
    tool_FUSION_TOKAMAK: 'Fusion Tokamak ⚛️',
    tool_BCI_SPELLER: 'BCI Neuro-Speller 🧠',
    tool_LEGAL_ANALYZER: 'Legal Analyzer ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'Exoplanet Photometry 🔭',
    tool_GRAVITATIONAL_WAVES: 'Gravitational Waves 🌌',
    tool_ROBOTICS_KINEMATICS: 'Robotics Kinematics 🤖',
    tool_EPIGENETIC_CLOCK: 'Epigenetic Clock ⏳',
    tool_COMMUNITY: 'Community Hub 👥',
    tool_LEADERBOARD: 'Leaderboards 🏆',
    tool_STUDY_ROOMS: 'Study Rooms 🎧',
    tool_STUDY_SWARM: 'Study Swarm 🤖',
    tool_QUIZ_BATTLE: '1v1 Arena ⚔️',
    tool_HACKATHON_RADAR: 'Hackathons 🏆',
    tool_HACKATHON_WAR_ROOM: 'Hackathon War-Room ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'Knowledge Olympiad 🏆',
    tool_FACULTY_ADVISORY: 'Faculty Advisory 🎓',
    tool_ALUMNI_RADAR: 'Alumni Mentors 🌐',
    tool_TUTOR_BOUNTY: 'Tutor Bounty 💰',
    tool_STUDY_GUILD_DAO: 'Guild DAO 🏛️',
    tool_CAMPUS_EXCHANGE: 'Campus Exchange 📦',
    tool_NOTES_MARKETPLACE: 'Notes Bazaar 🛍️',
    tool_HOSTEL_NUTRITION: 'Hostel Mess 🥗',
    tool_CAMPUS_TRANSIT: 'Campus Transit 🚌',
    tool_CAMPUS_PRINTING: 'Campus Print 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'Campus Twin 🗺️',
    tool_VIRTUAL_CAMPUS: '2D Campus 🏰',
    tool_DEADLINES: 'Deadlines & Alerts 🚨',
    tool_FOCUS_GARDEN: 'Focus Garden 🌲',
    tool_CIRCADIAN_FOCUS: 'Circadian Focus ⚡',
    tool_NEURAL_FLOW: 'Neural Flow 🧠',
    tool_MENTAL_RESILIENCE: 'Resilience Sanctum 🧘',
    tool_ERGONOMIC_WELLNESS: 'Ergonomics Bio-Cam 👁️',
    tool_CARBON_MARKET: 'Carbon Market 🌱',

    // View Components & Actions
    phase_badge: 'PHASE 53 • CAMPUS RESOURCE BAZAAR',
    verified_registry: 'Verified Student Registry',
    campus_exchange_title: 'Smart Campus Lost & Found',
    campus_exchange_title_accent: '& Equipment Exchange 🎒',
    campus_exchange_desc: 'Report lost items, claim found IDs & scientific calculators, and borrow lab drafters & robotics kits from verified peers.',
    report_share_btn: '+ Report / Share Item',
    filter_all: 'ALL',
    filter_lost: 'LOST',
    filter_found: 'FOUND',
    filter_borrow: 'FOR BORROW / RENT',
    search_items_placeholder: 'Search items or location...',
    badge_lost: 'LOST ITEM 🔍',
    badge_found: 'FOUND ITEM 🎁',
    badge_borrow: 'BORROW / RENT 🤝',
    mark_resolved: 'Mark Resolved',
    mark_borrowed: 'Mark Borrowed',
    status_resolved: 'RESOLVED',
    status_claimed: 'CLAIMED',
    report_modal_title: 'Report Lost / Found / Share Equipment 🎒',
    field_type: 'Type',
    field_category: 'Category',
    field_title: 'Item Title',
    field_location: 'Location Details',
    field_desc: 'Description & Identifiers',
    field_contact: 'Contact (Telegram / WhatsApp / Email)',
    btn_cancel: 'Cancel',
    btn_publish: 'Publish Item',
    opt_lost: 'Lost Item',
    opt_found: 'Found Item',
    opt_borrow: 'Available for Borrowing',
    opt_calculator: 'Scientific Calculator',
    opt_id_card: 'ID Card / Document',
    opt_lab_equipment: 'Lab Drafter / Tools',
    opt_book_notes: 'Notes / Book',
    opt_electronics: 'Electronics / Cables'
  },

  hinglish: {
    // Nav & System
    app_subtitle: 'Study, Exams & Career ke liye Ultimate Operating System',
    cockpit: 'Cockpit 🚀',
    academics: 'Academics 📚',
    academics_full: 'Academics & Exams Engine',
    ai_copilot: 'AI Copilot 🤖',
    ai_copilot_full: 'AI Study Tools & Studio',
    career: 'Career & Gigs 💼',
    career_full: 'Career, Resume & Launchpad',
    labs: 'Research & Labs 🔬',
    labs_full: 'DeepTech, Coding & Research Labs',
    community: 'Campus Hub 👥',
    community_full: 'Community, Battles & Arena',
    campus: 'Campus & Health 🏫',
    campus_full: 'Campus Life, Mess & Wellness',
    grandmaster: 'Grandmaster 👑',
    roadmap: 'Roadmap 🗺️',
    search: 'Search karo',
    api_online: 'ONLINE ✅',
    api_standby: 'STANDBY',
    daily_digest: 'Daily Digest ☀️',
    sign_in: 'Sign In / Login',
    sign_out: 'Log Out',

    // Dashboard & Student Card
    level_scholar: 'LEVEL {level} SCHOLAR 🎓',
    total_xp: 'Total XP Points',
    xp_needed: 'XP aur chahiye',
    day_streak: 'Day Streak 🔥',
    edit_profile: 'Profile Edit Karo',
    daily_study_target: 'Daily Study Target ⏱️',
    target_exams: 'Target Exams 🎯',
    dream_career: 'Dream Career Goal 💼',
    skills: 'Skills & Mastery',

    // Focus & Progress
    smart_focus_engine: 'Smart Focus Engine ⏱️',
    pomodoro_protocol: 'Pomodoro Deep Focus Protocol',
    focus_25: '25m Focus',
    focus_50: '50m Deep Work',
    break_5: '5m Short Break',
    study_commitment: 'Aaj Ka Study Target Progress',
    daily_telemetry: 'Daily target telemetry aur metrics',
    time_studied_today: 'Aaj Kitni Padhai Ki:',
    target_label: 'Target:',
    remaining_label: 'Baki Time:',

    // Exams & Revision
    target_exam_countdowns: 'Target Exam Countdowns ⏳',
    milestone_tracker: 'Upcoming exam milestones aur countdowns',
    view_prep_hub: 'Prep Hub Dekho',
    days_left: 'din baki hain',
    spaced_repetition_queue: 'Spaced Repetition Queue (SM-2) 🧠',
    memory_curve: 'Active recall memory decay curve',
    start_rapid_review: 'Rapid Review Shuru Karo ⚡',
    due_today: 'cards aaj revision ke liye pending hain',
    estimated_time: 'Lagbhag time',

    // AI Accelerators
    ai_shortcuts_title: 'AI Study & Mentor Shortcuts 🤖✨',
    ai_shortcuts_sub: 'Instant context-aware acceleration tools',
    summarize_notes: 'Notes Summarize Karo',
    generate_flashcards: 'Flashcards Banao',
    ask_ai_mentor: 'AI Mentor Se Poochho',
    quote_text: '"Roz ki chhoti-chhoti mehnat aur consistency hi exam me top rank dilati hai."',
    quote_author: '— Daily Motivation',

    // Live Telemetry & Footer
    live_telemetry: 'Live Telemetry 📡',
    streaming: 'STREAMING 🟢',
    paused: 'PAUSED ⏸️',
    footer_text: 'StudentLife OS 16.0 (Century Grandmaster Edition) • 100/100 Phases Fully Operational • 100% Production Ready 🏆💯',

    // Tool Ribbon Names
    tool_PLANNER: 'Study Planner 📅',
    tool_SYLLABUS: 'Syllabus Tracker 🌲',
    tool_NOTES: 'Notes Hub 📝',
    tool_REVISION: 'SM-2 Revision 🧠',
    tool_EXAM_PREP: 'Exam Mode 🎯',
    tool_QUESTION_BANK: 'PYQ Question Bank 📚',
    tool_MOCK_TEST: 'Mock Test Simulator ⏱️',
    tool_CUSTOM_PAPER: 'Exam Paper Generator 📜',
    tool_RANK_PREDICTOR: 'AIR Rank Predictor 🎯',
    tool_EXAM_TREND: 'Cutoff Trends 🔮',
    tool_ANKI_FSRS: 'Anki FSRS Sync 🔄',
    tool_ACADEMIC_INTEGRITY: 'Integrity Shield 🛡️',
    tool_ANALYTICS: 'Performance Analytics 📈',
    tool_AI_STUDY: 'AI Study Assistant 🤖',
    tool_AI_MENTOR: 'AI Mentor 360° 🎓',
    tool_VOICE_TUTOR: 'Voice Tutor 🎙️',
    tool_AI_PODCAST: 'AI Podcast 🎙️',
    tool_SOCRATIC_DEBATE: 'Socratic Debate ⚖️',
    tool_CONCEPT_GRAPH: 'Mind Map Graph 🕸️',
    tool_AI_WHITEBOARD: 'AI Whiteboard 🎨',
    tool_DOCUMENT_ANNOTATOR: 'PDF Annotator 📝',
    tool_OCR_SCANNER: 'OCR Scanner 📷',
    tool_VIDEO_NAVIGATOR: 'Video Navigator 🎬',
    tool_SPEED_READER: 'Speed Reader ⚡',
    tool_POLYGLOT_TRANSLATOR: 'Polyglot Translator 🌐',
    tool_SLIDE_GENERATOR: 'Slide Studio 📊',
    tool_CAREER: 'Career Intel 💼',
    tool_RESUME: 'ATS Resume Builder 📄',
    tool_INTERNSHIPS: 'Internship Portal 🎯',
    tool_SCHOLARSHIPS: 'Scholarship Finder 🏆',
    tool_MOCK_INTERVIEW: 'Viva & AI Interview 🎙️',
    tool_STUDENT_FINANCES: 'Budget & Gigs 💳',
    tool_MICRO_INTERNSHIP: 'Micro-Gigs Escrow 💼',
    tool_CAMPUS_INCUBATOR: 'Startup Incubator 🚀',
    tool_FELLOWSHIP_DRAFTER: 'Fellowship Drafter 🏅',
    tool_SKILL_PASSPORT: 'Skill Passport 🎖️',
    tool_VENTURE_SAFE: 'Venture SAFE 💼',
    tool_HFT_ORDERBOOK: 'HFT Order Book 📈',
    tool_RESEARCH_LAB: 'AI Research Lab 🧬',
    tool_ARXIV_SCHOLAR: 'arXiv Scholar 📄',
    tool_CODE_SANDBOX: 'Code Sandbox 💻',
    tool_LATEX_STUDIO: 'LaTeX Studio 📐',
    tool_PATENT_DRAFTER: 'Patent Drafter 📜',
    tool_HOLO_SIMULATIONS: '3D Holo-Lab 🧬',
    tool_QUANTUM_LAB: 'Quantum Lab ⚛️',
    tool_QUANTUM_QKD: 'Quantum QKD 🔑',
    tool_LAB_NOTEBOOK: 'Lab Notebook 🧪',
    tool_KERNEL_PROFILER: 'Kernel Profiler ⚡',
    tool_ASTRODYNAMICS: 'Astrodynamics Sim 🪐',
    tool_CHEMICAL_RETRO: 'Retrosynthesis 🧪',
    tool_SCHOLAR_TRACKER: 'Scholar Tracker 🎓',
    tool_NEUROMORPHIC_SNN: 'Neuromorphic SNN 🧠',
    tool_PAPER_REFEREE: 'Peer Reviewer 📝',
    tool_CRISPR_EDITOR: 'CRISPR Gene Editor 🧬',
    tool_FUSION_TOKAMAK: 'Fusion Tokamak ⚛️',
    tool_BCI_SPELLER: 'BCI Neuro-Speller 🧠',
    tool_LEGAL_ANALYZER: 'Legal Briefs ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'Exoplanet Transit 🔭',
    tool_GRAVITATIONAL_WAVES: 'Gravitational Waves 🌌',
    tool_ROBOTICS_KINEMATICS: 'Robotics Kinematics 🤖',
    tool_EPIGENETIC_CLOCK: 'Epigenetic Clock ⏳',
    tool_COMMUNITY: 'Campus Feed 👥',
    tool_LEADERBOARD: 'Leaderboards 🏆',
    tool_STUDY_ROOMS: 'Live Study Rooms 🎧',
    tool_STUDY_SWARM: 'Study Swarm 🤖',
    tool_QUIZ_BATTLE: '1v1 Battle Arena ⚔️',
    tool_HACKATHON_RADAR: 'Hackathon Radar 🏆',
    tool_HACKATHON_WAR_ROOM: 'War Room ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'Knowledge Olympiad 🏆',
    tool_FACULTY_ADVISORY: 'Faculty Advisory 🎓',
    tool_ALUMNI_RADAR: 'Alumni Mentors 🌐',
    tool_TUTOR_BOUNTY: 'Tutor Bounty 💰',
    tool_STUDY_GUILD_DAO: 'Guild DAO 🏛️',
    tool_CAMPUS_EXCHANGE: 'Campus Exchange 📦',
    tool_NOTES_MARKETPLACE: 'Notes Bazaar 🛍️',
    tool_HOSTEL_NUTRITION: 'Hostel Mess 🥗',
    tool_CAMPUS_TRANSIT: 'Campus Transit 🚌',
    tool_CAMPUS_PRINTING: 'Campus Print 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'Campus Twin 🗺️',
    tool_VIRTUAL_CAMPUS: '2D Campus 🏰',
    tool_DEADLINES: 'Deadlines & Alerts 🚨',
    tool_FOCUS_GARDEN: 'Focus Garden 🌲',
    tool_CIRCADIAN_FOCUS: 'Circadian Focus ⚡',
    tool_NEURAL_FLOW: 'Neural Flow 🧠',
    tool_MENTAL_RESILIENCE: 'Resilience Sanctum 🧘',
    tool_ERGONOMIC_WELLNESS: 'Ergonomics Bio-Cam 👁️',
    tool_CARBON_MARKET: 'Carbon Market 🌱',

    // View Components & Actions
    phase_badge: 'PHASE 53 • CAMPUS RESOURCE BAZAAR',
    verified_registry: 'Verified Student Registry ✅',
    campus_exchange_title: 'Smart Campus Lost & Found',
    campus_exchange_title_accent: '& Equipment Exchange 🎒',
    campus_exchange_desc: 'Khoi hui cheezein dhundo, found items claim karo, aur dosto se drafters ya kits borrow karo.',
    report_share_btn: '+ Item Report / Share Karo',
    filter_all: 'SABHI',
    filter_lost: 'KHO GAYA (LOST)',
    filter_found: 'MILA (FOUND)',
    filter_borrow: 'UDHAAR / RENT',
    search_items_placeholder: 'Item ya location search karo...',
    badge_lost: 'KHO GAYA 🔍',
    badge_found: 'MILA HUA 🎁',
    badge_borrow: 'UDHAAR / RENT 🤝',
    mark_resolved: 'Resolved Mark Karo',
    mark_borrowed: 'Borrowed Mark Karo',
    status_resolved: 'RESOLVED',
    status_claimed: 'CLAIMED',
    report_modal_title: 'Lost / Found Item Report Ya Share Karo 🎒',
    field_type: 'Type',
    field_category: 'Category',
    field_title: 'Item Ka Naam',
    field_location: 'Kaha Mila / Kaha Khoya',
    field_desc: 'Description & Pehchan',
    field_contact: 'Contact Info (Telegram / WhatsApp / Email)',
    btn_cancel: 'Cancel',
    btn_publish: 'Item Publish Karo',
    opt_lost: 'Khoyi Hui Cheez (Lost)',
    opt_found: 'Mili Hui Cheez (Found)',
    opt_borrow: 'Udhaar Ke Liye Available',
    opt_calculator: 'Scientific Calculator',
    opt_id_card: 'ID Card / Document',
    opt_lab_equipment: 'Lab Drafter / Tools',
    opt_book_notes: 'Notes / Kitab',
    opt_electronics: 'Electronics / Cables'
  },

  hi: {
    // Nav & System
    app_subtitle: 'अध्ययन, परीक्षा और करियर के लिए सम्पूर्ण ऑपरेटिंग सिस्टम',
    cockpit: 'कॉकपिट 🚀',
    academics: 'अकादमिक 📚',
    academics_full: 'अकादमिक और परीक्षा केंद्र',
    ai_copilot: 'AI कोपायलट 🤖',
    ai_copilot_full: 'AI अध्ययन टूल्स व स्टूडियो',
    career: 'करियर व गिग्स 💼',
    career_full: 'करियर, रिज्यूमे व अवसर',
    labs: 'रिसर्च व लैब्स 🔬',
    labs_full: 'डीप-टेक, कोडिंग व रिसर्च लैब्स',
    community: 'कैंपस हब 👥',
    community_full: 'समुदाय, क्विज़ व अखाड़ा',
    campus: 'कैंपस व स्वास्थ्य 🏫',
    campus_full: 'कैंपस जीवन, मेस व वेलनेस',
    grandmaster: 'ग्रैंडमास्टर 👑',
    roadmap: 'रोडमैप 🗺️',
    search: 'खोजें',
    api_online: 'सक्रिय (ONLINE)',
    api_standby: 'प्रतीक्षारत',
    daily_digest: 'दैनिक डाइजेस्ट ☀️',
    sign_in: 'साइन इन / लॉगिन',
    sign_out: 'लॉग आउट',

    // Dashboard & Student Card
    level_scholar: 'लेवल {level} स्कॉलर 🎓',
    total_xp: 'कुल अर्जित XP',
    xp_needed: 'अगले लेवल हेतु XP',
    day_streak: 'दैनिक स्ट्रीक 🔥',
    edit_profile: 'प्रोफ़ाइल बदलें',
    daily_study_target: 'दैनिक अध्ययन लक्ष्य ⏱️',
    target_exams: 'लक्षित परीक्षाएँ 🎯',
    dream_career: 'सपनों का करियर 💼',
    skills: 'कौशल एवं दक्षताएं',

    // Focus & Progress
    smart_focus_engine: 'स्मार्ट फोकस इंजन ⏱️',
    pomodoro_protocol: 'पोमोडोरो डीप वर्क प्रोटोकॉल',
    focus_25: '25 मिनट एकाग्रता',
    focus_50: '50 मिनट गहन अध्ययन',
    break_5: '5 मिनट विश्राम',
    study_commitment: 'आज का अध्ययन संकल्प',
    daily_telemetry: 'दैनिक प्रगति ट्रैकर',
    time_studied_today: 'आज का अध्ययन समय:',
    target_label: 'लक्ष्य:',
    remaining_label: 'शेष समय:',

    // Exams & Revision
    target_exam_countdowns: 'परीक्षा उल्टी गिनती ⏳',
    milestone_tracker: 'आगामी परीक्षा उलटी गिनती',
    view_prep_hub: 'तैयारी केंद्र देखें',
    days_left: 'दिन शेष',
    spaced_repetition_queue: 'स्मृति पुनरावृत्ति कतार (SM-2) 🧠',
    memory_curve: 'दीर्घकालिक स्मृति व पुनरावृत्ति ट्रैकर',
    start_rapid_review: 'रिवीजन शुरू करें ⚡',
    due_today: 'कार्ड आज पुनरावृत्ति हेतु लंबित हैं',
    estimated_time: 'अनुमानित समय',

    // AI Accelerators
    ai_shortcuts_title: 'AI अध्ययन व मेंटर शॉर्टकट्स 🤖✨',
    ai_shortcuts_sub: 'त्वरित संदर्भ-सक्षम अध्ययन साधन',
    summarize_notes: 'नोट्स का सारांश बनाएँ',
    generate_flashcards: 'फ्लैशकार्ड्स तैयार करें',
    ask_ai_mentor: 'AI मेंटर से पूछें',
    quote_text: '"निरंतर अभ्यास और अनुशासन से ही असाधारण शैक्षणिक सफलता प्राप्त होती है।"',
    quote_author: '— दैनिक सुविचार',

    // Live Telemetry & Footer
    live_telemetry: 'लाइव टेलीमेट्री 📡',
    streaming: 'प्रसारण जारी 🟢',
    paused: 'रोका गया ⏸️',
    footer_text: 'StudentLife OS 16.0 (सेंचुरी ग्रैंडमास्टर संस्करण) • 100/100 चरण पूर्णतः क्रियाशील • 100% प्रोडक्शन रेडी 🏆💯',

    // Tool Ribbon Names
    tool_PLANNER: 'अध्ययन योजनाकार 📅',
    tool_SYLLABUS: 'पाठ्यक्रम ट्रैकर 🌲',
    tool_NOTES: 'नोट्स संग्रह 📝',
    tool_REVISION: 'SM-2 रिवीजन 🧠',
    tool_EXAM_PREP: 'परीक्षा तैयारी 🎯',
    tool_QUESTION_BANK: 'प्रश्न बैंक (PYQ) 📚',
    tool_MOCK_TEST: 'मॉक टेस्ट सिम्युलेटर ⏱️',
    tool_CUSTOM_PAPER: 'प्रश्न पत्र निर्माता 📜',
    tool_RANK_PREDICTOR: 'रैंक भविष्यवक्ता 🎯',
    tool_EXAM_TREND: 'कटऑफ रुझान 🔮',
    tool_ANKI_FSRS: 'अंकी FSRS सिंक 🔄',
    tool_ACADEMIC_INTEGRITY: 'अकादमिक सत्यनिष्ठा 🛡️',
    tool_ANALYTICS: 'प्रदर्शन विश्लेषण 📈',
    tool_AI_STUDY: 'AI अध्ययन सहायक 🤖',
    tool_AI_MENTOR: 'AI मेंटर 360° 🎓',
    tool_VOICE_TUTOR: 'वॉइस ट्यूटर 🎙️',
    tool_AI_PODCAST: 'AI पॉडकास्ट 🎙️',
    tool_SOCRATIC_DEBATE: 'सुकराती संवाद ⚖️',
    tool_CONCEPT_GRAPH: 'माइंड मैप ग्राफ 🕸️',
    tool_AI_WHITEBOARD: 'AI व्हाइटबोर्ड 🎨',
    tool_DOCUMENT_ANNOTATOR: 'PDF एनोटेटर 📝',
    tool_OCR_SCANNER: 'OCR स्कैनर 📷',
    tool_VIDEO_NAVIGATOR: 'वीडियो नेविगेटर 🎬',
    tool_SPEED_READER: 'स्पीड रीडर ⚡',
    tool_POLYGLOT_TRANSLATOR: 'बहुभाषी अनुवादक 🌐',
    tool_SLIDE_GENERATOR: 'स्लाइड स्टूडियो 📊',
    tool_CAREER: 'करियर मार्गदर्शन 💼',
    tool_RESUME: 'ATS रिज्यूमे निर्माता 📄',
    tool_INTERNSHIPS: 'इंटर्नशिप पोर्टल 🎯',
    tool_SCHOLARSHIPS: 'छात्रवृत्ति खोजक 🏆',
    tool_MOCK_INTERVIEW: 'मॉक इंटरव्यू 🎙️',
    tool_STUDENT_FINANCES: 'छात्र वित्त व बजट 💳',
    tool_MICRO_INTERNSHIP: 'माइक्रो-गिग्स एस्क्रो 💼',
    tool_CAMPUS_INCUBATOR: 'स्टार्टअप इनक्यूबेटर 🚀',
    tool_FELLOWSHIP_DRAFTER: 'फेलोशिप ड्राफ्टर 🏅',
    tool_SKILL_PASSPORT: 'स्किल पासपोर्ट 🎖️',
    tool_VENTURE_SAFE: 'वेंचर सेफ 💼',
    tool_HFT_ORDERBOOK: 'HFT ऑर्डर बुक 📈',
    tool_RESEARCH_LAB: 'AI रिसर्च लैब 🧬',
    tool_ARXIV_SCHOLAR: 'arXiv स्कॉलर 📄',
    tool_CODE_SANDBOX: 'कोड सैंडबॉक्स 💻',
    tool_LATEX_STUDIO: 'LaTeX स्टूडियो 📐',
    tool_PATENT_DRAFTER: 'पेटेंट व IP 📜',
    tool_HOLO_SIMULATIONS: '3D होलो-लैब 🧬',
    tool_QUANTUM_LAB: 'क्वांटम लैब ⚛️',
    tool_QUANTUM_QKD: 'क्वांटम QKD 🔑',
    tool_LAB_NOTEBOOK: 'लैब नोटबुक 🧪',
    tool_KERNEL_PROFILER: 'कर्नेल प्रोफाइलर ⚡',
    tool_ASTRODYNAMICS: 'खगोल विज्ञान सिम्युलेटर 🪐',
    tool_CHEMICAL_RETRO: 'रासायनिक संश्लेषण 🧪',
    tool_SCHOLAR_TRACKER: 'विद्वान ट्रैकर 🎓',
    tool_NEUROMORPHIC_SNN: 'न्यूरोमॉर्फिक SNN 🧠',
    tool_PAPER_REFEREE: 'सहकर्मी समीक्षक 📝',
    tool_CRISPR_EDITOR: 'CRISPR जीन संपादक 🧬',
    tool_FUSION_TOKAMAK: 'फ्यूजन टोकामक ⚛️',
    tool_BCI_SPELLER: 'BCI न्यूरो-स्पेलर 🧠',
    tool_LEGAL_ANALYZER: 'कानूनी विश्लेषक ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'बाह्यग्रह प्रकाशमिति 🔭',
    tool_GRAVITATIONAL_WAVES: 'गुरुत्वाकर्षण तरंगें 🌌',
    tool_ROBOTICS_KINEMATICS: 'रोबोटिक्स गतिकी 🤖',
    tool_EPIGENETIC_CLOCK: 'एपिजेनेटिक घड़ी ⏳',
    tool_COMMUNITY: 'कैंपस समुदाय 👥',
    tool_LEADERBOARD: 'लीडरबोर्ड 🏆',
    tool_STUDY_ROOMS: 'लाइव अध्ययन कक्ष 🎧',
    tool_STUDY_SWARM: 'अध्ययन झुंड 🤖',
    tool_QUIZ_BATTLE: '1v1 प्रश्नोत्तरी अखाड़ा ⚔️',
    tool_HACKATHON_RADAR: 'हैकाथॉन रडार 🏆',
    tool_HACKATHON_WAR_ROOM: 'हैकाथॉन वॉर-रूम ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'ज्ञान ओलंपियाड 🏆',
    tool_FACULTY_ADVISORY: 'संकाय सलाह 🎓',
    tool_ALUMNI_RADAR: 'पूर्व छात्र मेंटर्स 🌐',
    tool_TUTOR_BOUNTY: 'ट्यूटर बाउंटी 💰',
    tool_STUDY_GUILD_DAO: 'गिल्ड DAO 🏛️',
    tool_CAMPUS_EXCHANGE: 'कैंपस एक्सचेंज 📦',
    tool_NOTES_MARKETPLACE: 'नोट्स बाज़ार 🛍️',
    tool_HOSTEL_NUTRITION: 'हॉस्टल मेस 🥗',
    tool_CAMPUS_TRANSIT: 'कैंपस ट्रांजिट 🚌',
    tool_CAMPUS_PRINTING: 'कैंपस प्रिंटिंग 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'डिजिटल ट्विन 🗺️',
    tool_VIRTUAL_CAMPUS: '2D कैंपस 🏰',
    tool_DEADLINES: 'अंतिम तिथियां व अलर्ट 🚨',
    tool_FOCUS_GARDEN: 'फोकस गार्डन 🌲',
    tool_CIRCADIAN_FOCUS: 'सर्केडियन रिदम ⚡',
    tool_NEURAL_FLOW: 'न्यूरल फ्लो 🧠',
    tool_MENTAL_RESILIENCE: 'मानसिक लचीलापन 🧘',
    tool_ERGONOMIC_WELLNESS: 'शारीरिक मुद्रा एवं स्वास्थ्य 👁️',
    tool_CARBON_MARKET: 'कार्बन बाजार 🌱',

    // View Components & Actions
    phase_badge: 'चरण 53 • कैंपस संसाधन बाज़ार',
    verified_registry: 'सत्यापित छात्र रजिस्ट्री ✅',
    campus_exchange_title: 'स्मार्ट कैंपस खोया-पाया',
    campus_exchange_title_accent: 'व उपकरण विनिमय 🎒',
    campus_exchange_desc: 'खोई हुई वस्तुओं की रिपोर्ट करें, मिले हुए पहचान पत्र व कैलकुलेटर प्राप्त करें, एवं सहपाठियों से ड्राफ्टर्स व रोबोटिक्स किट उधार लें।',
    report_share_btn: '+ वस्तु रिपोर्ट / साझा करें',
    filter_all: 'सभी वस्तुएं',
    filter_lost: 'खोया हुआ (LOST)',
    filter_found: 'मिला हुआ (FOUND)',
    filter_borrow: 'उधार / रेंट हेतु',
    search_items_placeholder: 'वस्तु या स्थान खोजें...',
    badge_lost: 'खोई हुई वस्तु 🔍',
    badge_found: 'मिली हुई वस्तु 🎁',
    badge_borrow: 'उधार / साझा 🤝',
    mark_resolved: 'निस्तारित मार्क करें',
    mark_borrowed: 'उधार दिया मार्क करें',
    status_resolved: 'निस्तारित (RESOLVED)',
    status_claimed: 'प्राप्त (CLAIMED)',
    report_modal_title: 'खोई/मिली वस्तु की रिपोर्ट या साझा करें 🎒',
    field_type: 'प्रकार',
    field_category: 'श्रेणी',
    field_title: 'वस्तु का नाम',
    field_location: 'स्थान विवरण',
    field_desc: 'विवरण व पहचान चिह्न',
    field_contact: 'संपर्क (टेलीग्राम / व्हाट्सएप / ईमेल)',
    btn_cancel: 'रद्द करें',
    btn_publish: 'वस्तु प्रकाशित करें',
    opt_lost: 'खोई हुई वस्तु',
    opt_found: 'मिली हुई वस्तु',
    opt_borrow: 'उधार के लिए उपलब्ध',
    opt_calculator: 'वैज्ञानिक कैलकुलेटर',
    opt_id_card: 'आईडी कार्ड / दस्तावेज',
    opt_lab_equipment: 'लैब ड्राफ्टर / उपकरण',
    opt_book_notes: 'नोट्स / पुस्तकें',
    opt_electronics: 'इलेक्ट्रॉनिक्स / केबल्स'
  },

  bn: {
    app_subtitle: 'পড়াশোনা, পরীক্ষা ও ক্যারিয়ারের সম্পূর্ণ অপারেটিং সিস্টেম',
    cockpit: 'ককপিট 🚀',
    academics: 'একাডেমিক 📚',
    academics_full: 'একাডেমিক ও পরীক্ষা ব্যবস্থা',
    ai_copilot: 'এআই কোপাইলট 🤖',
    ai_copilot_full: 'এআই স্টাডি টুলস ও স্টুডিও',
    career: 'ক্যারিয়ার ও সুযোগ 💼',
    career_full: 'ক্যারিয়ার ও ইন্টার্নশিপ',
    labs: 'গবেষণা ও ল্যাব 🔬',
    labs_full: 'ডিপটেক ও সায়েন্স ল্যাব',
    community: 'ক্যাম্পাস হাব 👥',
    community_full: 'কমিউনিটি ও স্টাডি রুম',
    campus: 'ক্যাম্পাস ও স্বাস্থ্য 🏫',
    campus_full: 'ক্যাম্পাস জীবন ও সুস্থতা',
    grandmaster: 'গ্র্যান্ডমাস্টার 👑',
    roadmap: 'রোডম্যাপ 🗺️',
    search: 'অনুসন্ধান করুন',
    api_online: 'অনলাইন ✅',
    api_standby: 'স্ট্যান্ডবাই',
    daily_digest: 'দৈনিক ডাইজেস্ট ☀️',
    sign_in: 'লগইন / সাইন ইন',
    sign_out: 'লগ আউট',
    level_scholar: 'লেভেল {level} স্কলার 🎓',
    total_xp: 'মোট এক্সপি',
    xp_needed: 'প্রয়োজনীয় এক্সপি',
    day_streak: 'দিনের স্ট্রিক 🔥',
    edit_profile: 'প্রোফাইল পরিবর্তন',
    daily_study_target: 'দৈনিক পড়ার লক্ষ্য ⏱️',
    target_exams: 'টার্গেট পরীক্ষা 🎯',
    dream_career: 'স্বপ্নের ক্যারিয়ার 💼',
    skills: 'দক্ষতা',
    smart_focus_engine: 'স্মার্ট ফোকাস ইঞ্জিন ⏱️',
    pomodoro_protocol: 'পোমোডোরো ডিপ স্টাডি প্রোটোকল',
    focus_25: '২৫ মিনিট ফোকাস',
    focus_50: '৫০ মিনিট গভীর মনোযোগ',
    break_5: '৫ মিনিট বিরতি',
    study_commitment: 'আজকের পড়ার অগ্রগতি',
    daily_telemetry: 'দৈনিক লক্ষ্য ট্র্যাকার',
    time_studied_today: 'আজ পড়া হয়েছে:',
    target_label: 'টার্গেট:',
    remaining_label: 'বাকি সময়:',
    target_exam_countdowns: 'পরীক্ষার কাউন্টডাউন ⏳',
    milestone_tracker: 'আসন্ন পরীক্ষার সময়সূচী',
    view_prep_hub: 'প্রেপ হাব দেখুন',
    days_left: 'দিন বাকি',
    spaced_repetition_queue: 'রিভিশন কিউ (SM-2) 🧠',
    memory_curve: 'স্মৃতি ধরে রাখার গ্রাফ',
    start_rapid_review: 'রিভিশন শুরু করুন ⚡',
    due_today: 'টি কার্ড রিভিশন বাকি আছে',
    estimated_time: 'আনুমানিক সময়',
    ai_shortcuts_title: 'এআই স্টাডি ও মেন্টর 🤖✨',
    ai_shortcuts_sub: 'তাৎক্ষণিক এআই অ্যাক্সিলারেশন টুলস',
    summarize_notes: 'নোট সারসংক্ষেপ',
    generate_flashcards: 'ফ্ল্যাশকার্ড তৈরি',
    ask_ai_mentor: 'এআই মেন্টরকে জিজ্ঞাসা করুন',
    quote_text: '"প্রতিদিনের ছোট ছোট অনুশীলন ভবিষ্যতে অসাধারণ সাফল্য এনে দেয়।"',
    quote_author: '— অনুপ্রেরণা',
    live_telemetry: 'লাইভ টেলিমেট্রি 📡',
    streaming: 'স্ট্রিমিং 🟢',
    paused: 'স্থগিত ⏸️',
    footer_text: 'StudentLife OS 16.0 (গ্র্যান্ডমাস্টার সংস্করণ) • ১০০/১০০ ধাপ সম্পূর্ণ সচল 🏆💯',

    // Tools
    tool_PLANNER: 'স্টাডি প্ল্যানার 📅',
    tool_SYLLABUS: 'সিলেবাস ট্র্যাকার 🌲',
    tool_NOTES: 'নোটস সংগ্রহ 📝',
    tool_REVISION: 'রিভিশন ইঞ্জিন 🧠',
    tool_EXAM_PREP: 'পরীক্ষার প্রস্তুতি 🎯',
    tool_QUESTION_BANK: 'প্রশ্ন ব্যাংক (PYQ) 📚',
    tool_MOCK_TEST: 'মক টেস্ট ⏱️',
    tool_CUSTOM_PAPER: 'প্রশ্নপত্র জেনারেটর 📜',
    tool_RANK_PREDICTOR: 'র‌্যাংক প্রেডিক্টর 🎯',
    tool_EXAM_TREND: 'কাটঅফ ট্রেন্ডস 🔮',
    tool_ANKI_FSRS: 'আঙ্কি FSRS সিঙ্ক 🔄',
    tool_ACADEMIC_INTEGRITY: 'একাডেমিক নিরাপত্তা 🛡️',
    tool_ANALYTICS: 'পারফরম্যান্স অ্যানালিটিক্স 📈',
    tool_AI_STUDY: 'এআই স্টাডি অ্যাসিস্ট্যান্ট 🤖',
    tool_AI_MENTOR: 'এআই মেন্টর 🎓',
    tool_VOICE_TUTOR: 'ভয়েস টিউটর 🎙️',
    tool_AI_PODCAST: 'এআই পডকাস্ট 🎙️',
    tool_SOCRATIC_DEBATE: 'বিতর্ক ফোরাম ⚖️',
    tool_CONCEPT_GRAPH: 'কনসেপ্ট গ্রাফ 🕸️',
    tool_AI_WHITEBOARD: 'এআই হোয়াইটবোর্ড 🎨',
    tool_DOCUMENT_ANNOTATOR: 'পিডিএফ অ্যানোটেটর 📝',
    tool_OCR_SCANNER: 'ওসিআর স্ক্যানার 📷',
    tool_VIDEO_NAVIGATOR: 'ভিডিও নেভিগেটর 🎬',
    tool_SPEED_READER: 'স্পিড রিডার ⚡',
    tool_POLYGLOT_TRANSLATOR: 'অনুবাদক 🌐',
    tool_SLIDE_GENERATOR: 'স্লাইড স্টুডিও 📊',
    tool_CAREER: 'ক্যারিয়ার গাইডেন্স 💼',
    tool_RESUME: 'এভটিএস রিজিউমে 📄',
    tool_INTERNSHIPS: 'ইন্টার্নশিপ পোর্টাল 🎯',
    tool_SCHOLARSHIPS: 'স্কলারশিপ ফাইন্ডার 🏆',
    tool_MOCK_INTERVIEW: 'মক ইন্টারভিউ 🎙️',
    tool_STUDENT_FINANCES: 'ফাইন্যান্স ও বাজেট 💳',
    tool_MICRO_INTERNSHIP: 'মাইক্রো-গিগস 💼',
    tool_CAMPUS_INCUBATOR: 'স্টার্টআপ ইনকিউবেটর 🚀',
    tool_FELLOWSHIP_DRAFTER: 'ফেলোশিপ ড্রাফটার 🏅',
    tool_SKILL_PASSPORT: 'স্কিল পাসপোর্ট 🎖️',
    tool_VENTURE_SAFE: 'ভেঞ্চার সেফ 💼',
    tool_HFT_ORDERBOOK: 'অর্ডার বুক 📈',
    tool_RESEARCH_LAB: 'এআই রিসার্চ ল্যাব 🧬',
    tool_ARXIV_SCHOLAR: 'আর্কাইভ স্কলার 📄',
    tool_CODE_SANDBOX: 'কোড স্যান্ডবক্স 💻',
    tool_LATEX_STUDIO: 'লাটেক্স স্টুডিও 📐',
    tool_PATENT_DRAFTER: 'পেটেন্ট ও আইপি 📜',
    tool_HOLO_SIMULATIONS: 'থ্রিডি হোলো-ল্যাব 🧬',
    tool_QUANTUM_LAB: 'কোয়ান্টাম ল্যাব ⚛️',
    tool_QUANTUM_QKD: 'কোয়ান্টাম QKD 🔑',
    tool_LAB_NOTEBOOK: 'ল্যাব নোটবুক 🧪',
    tool_KERNEL_PROFILER: 'কার্নেল প্রোফাইলার ⚡',
    tool_ASTRODYNAMICS: 'অ্যাস্ট্রোডাইনামিক্স 🪐',
    tool_CHEMICAL_RETRO: 'কেমিক্যাল রিট্রোসিন্থেসিস 🧪',
    tool_SCHOLAR_TRACKER: 'স্কলার ট্র্যাকার 🎓',
    tool_NEUROMORPHIC_SNN: 'নিউরোমরফিক এসএনএন 🧠',
    tool_PAPER_REFEREE: 'পিয়ার রিভিউয়ার 📝',
    tool_CRISPR_EDITOR: 'জিন এডিটর 🧬',
    tool_FUSION_TOKAMAK: 'ফিউশন টোকামাক ⚛️',
    tool_BCI_SPELLER: 'বিসিআই স্পেলার 🧠',
    tool_LEGAL_ANALYZER: 'আইন বিশ্লেষক ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'এক্সোপ্ল্যানেট সিমুলেটর 🔭',
    tool_GRAVITATIONAL_WAVES: 'মহাকর্ষীয় তরঙ্গ 🌌',
    tool_ROBOTICS_KINEMATICS: 'রোবোটিক্স 🤖',
    tool_EPIGENETIC_CLOCK: 'এপিজেনেটিক ঘড়ি ⏳',
    tool_COMMUNITY: 'ক্যাম্পাস হাব 👥',
    tool_LEADERBOARD: 'লিডারবোর্ড 🏆',
    tool_STUDY_ROOMS: 'লাইভ স্টাডি রুম 🎧',
    tool_STUDY_SWARM: 'স্টাডি সোয়ার্ম 🤖',
    tool_QUIZ_BATTLE: 'কুইজ অ্যারেনা ⚔️',
    tool_HACKATHON_RADAR: 'হ্যাকাহন রাডার 🏆',
    tool_HACKATHON_WAR_ROOM: 'ওয়ার রুম ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'নলেজ অলিম্পিয়াড 🏆',
    tool_FACULTY_ADVISORY: 'অনুষদ পরামর্শ 🎓',
    tool_ALUMNI_RADAR: 'অ্যালামনাই মেন্টরস 🌐',
    tool_TUTOR_BOUNTY: 'টিউটর বাউন্টি 💰',
    tool_STUDY_GUILD_DAO: 'গিল্ড ডিএও 🏛️',
    tool_CAMPUS_EXCHANGE: 'ক্যাম্পাস এক্সচেঞ্জ 📦',
    tool_NOTES_MARKETPLACE: 'নোটস বাজার 🛍️',
    tool_HOSTEL_NUTRITION: 'হোস্টেল মেস 🥗',
    tool_CAMPUS_TRANSIT: 'ক্যাম্পাস ট্রানজিট 🚌',
    tool_CAMPUS_PRINTING: 'ক্যাম্পাস প্রিন্ট 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'ডিজিটাল টুইন 🗺️',
    tool_VIRTUAL_CAMPUS: 'টু-ডি ক্যাম্পাস 🏰',
    tool_DEADLINES: 'ডেডলাইন ও নোটিশ 🚨',
    tool_FOCUS_GARDEN: 'ফোকাস গার্ডেন 🌲',
    tool_CIRCADIAN_FOCUS: 'সার্কেডিয়ান ফোকাস ⚡',
    tool_NEURAL_FLOW: 'নিউরাল ফ্লো 🧠',
    tool_MENTAL_RESILIENCE: 'মানসিক সুস্থতা 🧘',
    tool_ERGONOMIC_WELLNESS: 'শারীরিক অঙ্গভঙ্গি স্বাস্থ্য 👁️',
    tool_CARBON_MARKET: 'কার্বন মার্কেট 🌱',

    // View components
    phase_badge: 'পর্যায় ৫৩ • ক্যাম্পাস রিসোর্স বাজার',
    verified_registry: 'যাচাইকৃত শিক্ষার্থী তালিকা ✅',
    campus_exchange_title: 'স্মার্ট ক্যাম্পাস লস্ট অ্যান্ড ফাউন্ড',
    campus_exchange_title_accent: 'ও সরঞ্জাম বিনিময় 🎒',
    campus_exchange_desc: 'হারানো জিনিসের রিপোর্ট করুন, আইডি কার্ড ও সায়েন্টিফিক ক্যালকুলেটর সংগ্রহ করুন এবং সহপাঠীদের থেকে সরঞ্জাম ধার নিন।',
    report_share_btn: '+ আইটেম রিপোর্ট / শেয়ার করুন',
    filter_all: 'সব আইটেম',
    filter_lost: 'হারানো (LOST)',
    filter_found: 'পাওয়া গেছে (FOUND)',
    filter_borrow: 'ধার / ভাড়ার জন্য',
    search_items_placeholder: 'আইটেম বা অবস্থান খুঁজুন...',
    badge_lost: 'হারানো জিনিস 🔍',
    badge_found: 'প্রাপ্ত জিনিস 🎁',
    badge_borrow: 'ধার / ভাড়া 🤝',
    mark_resolved: 'সমাধান হয়েছে চিহ্নিত করুন',
    mark_borrowed: 'ধার দেওয়া হয়েছে',
    status_resolved: 'RESOLVED',
    status_claimed: 'CLAIMED',
    report_modal_title: 'হারানো / প্রাপ্ত / ধার দেওয়ার আইটেম রিপোর্ট করুন 🎒',
    field_type: 'ধরণ',
    field_category: 'বিভাগ',
    field_title: 'আইটেমের নাম',
    field_location: 'অবস্থানের বিবরণ',
    field_desc: 'বিবরণ ও সনাক্তকারী চিহ্ন',
    field_contact: 'যোগাযোগের মাধ্যম',
    btn_cancel: 'বাতিল',
    btn_publish: 'আইটেম প্রকাশ করুন',
    opt_lost: 'হারানো জিনিস',
    opt_found: 'পাওয়া জিনিস',
    opt_borrow: 'ধারের জন্য প্রস্তুত',
    opt_calculator: 'সায়েন্টিফিক ক্যালকুলেটর',
    opt_id_card: 'আইডি কার্ড / নথি',
    opt_lab_equipment: 'ল্যাব ড্রাফটার / সরঞ্জাম',
    opt_book_notes: 'নোটস / বই',
    opt_electronics: 'ইলেকট্রনিক্স / তার'
  },

  te: {
    app_subtitle: 'చదువు, పరీక్షలు మరియు కెరీర్ కోసం పూర్తి ఆపరేటింగ్ సిస్టమ్',
    cockpit: 'కాక్‌పిట్ 🚀',
    academics: 'అకడమిక్స్ 📚',
    academics_full: 'అకడమిక్స్ మరియు పరీక్షలు',
    ai_copilot: 'AI కోపైలట్ 🤖',
    ai_copilot_full: 'AI స్టడీ టూల్స్ & స్టూడియో',
    career: 'కెరీర్ & అవకాశాలు 💼',
    career_full: 'కెరీర్, రెజ్యూమ్ & ఉద్యోగాలు',
    labs: 'పరిశోధన & ల్యాబ్స్ 🔬',
    labs_full: 'డీప్‌టెక్ & సైన్స్ ల్యాబ్స్',
    community: 'క్యాంపస్ హబ్ 👥',
    community_full: 'కమ్యూనిటీ & అరేనా',
    campus: 'క్యాంపస్ & ఆరోగ్యం 🏫',
    campus_full: 'క్యాంపస్ లైఫ్ & వెల్‌నెస్',
    grandmaster: 'గ్రాండ్‌మాస్టర్ 👑',
    roadmap: 'రోడ్‌మ్యాప్ 🗺️',
    search: 'శోధించండి',
    api_online: 'ఆన్‌లైన్ ✅',
    api_standby: 'స్టాండ్‌బై',
    daily_digest: 'డైలీ డైజెస్ట్ ☀️',
    sign_in: 'లాగిన్ / సైన్ ఇన్',
    sign_out: 'లాగ్ అవుట్',
    level_scholar: 'లెవల్ {level} స్కాలర్ 🎓',
    total_xp: 'మొత్తం XP',
    xp_needed: 'తదుపరి లెవల్ XP',
    day_streak: 'రోజుల స్ట్రీక్ 🔥',
    edit_profile: 'ప్రొఫైల్ సవరణ',
    daily_study_target: 'రోజువారీ అధ్యయన లక్ష్యం ⏱️',
    target_exams: 'లక్ష్య పరీక్షలు 🎯',
    dream_career: 'డ్రీమ్ కెరీర్ 💼',
    skills: 'నైపుణ్యాలు',
    smart_focus_engine: 'స్మార్ట్ ఫోకస్ ఇంజిన్ ⏱️',
    pomodoro_protocol: 'పోమోడోరో డీప్ వర్క్ ప్రోటోకాల్',
    focus_25: '25 నిమిషాల ఏకాగ్రత',
    focus_50: '50 నిమిషాల తీవ్ర అధ్యయనం',
    break_5: '5 నిమిషాల విరామం',
    study_commitment: 'నేటి అధ్యయన పురోగతి',
    daily_telemetry: 'రోజువారీ లక్ష్య ట్రాకర్',
    time_studied_today: 'ఈ రోజు చదివిన సమయం:',
    target_label: 'లక్ష్యం:',
    remaining_label: 'మిగిలిన సమయం:',
    target_exam_countdowns: 'పరీక్షల కౌంట్‌డౌన్ ⏳',
    milestone_tracker: 'రాబోయే పరీక్షల కౌంట్‌డౌన్',
    view_prep_hub: 'ప్రిపరేషన్ హబ్ చూడండి',
    days_left: 'రోజులు మిగిలి ఉన్నాయి',
    spaced_repetition_queue: 'పునశ్చరణ క్యూ (SM-2) 🧠',
    memory_curve: 'మెమరీ నిలుపుదల గ్రాఫ్',
    start_rapid_review: 'రివిజన్ ప్రారంభించండి ⚡',
    due_today: 'కార్డులు రివిజన్ కోసం ఉన్నాయి',
    estimated_time: 'అంచనా సమయం',
    ai_shortcuts_title: 'AI స్టడీ షార్ట్‌కట్‌లు 🤖✨',
    ai_shortcuts_sub: 'తక్షణ AI సహాయక టూల్స్',
    summarize_notes: 'నోట్స్ సారాంశం',
    generate_flashcards: 'ఫ్లాష్‌కార్డ్‌లు సృష్టించండి',
    ask_ai_mentor: 'AI మెంటార్‌ను అడగండి',
    quote_text: '"నిరంతర క్రమశిక్షణ మరియు కృషి అద్భుతమైన విజయాలకు దారితీస్తాయి."',
    quote_author: '— ప్రేరణాత్మక ఆలోచన',
    live_telemetry: 'లైవ్ టెలిమెట్రీ 📡',
    streaming: 'స్ట్రీమింగ్ 🟢',
    paused: 'పాజ్ చేయబడింది ⏸️',
    footer_text: 'StudentLife OS 16.0 (గ్రాండ్‌మాస్టర్ ఎడిషన్) • 100/100 దశలు పూర్తిగా పనిచేస్తున్నాయి 🏆💯',

    // Tools
    tool_PLANNER: 'స్టడీ ప్లానర్ 📅',
    tool_SYLLABUS: 'సిలబస్ ట్రాకర్ 🌲',
    tool_NOTES: 'నోట్స్ హబ్ 📝',
    tool_REVISION: 'రివిజన్ ఇంజిన్ 🧠',
    tool_EXAM_PREP: 'ఎగ్జామ్ ప్రిపరేషన్ 🎯',
    tool_QUESTION_BANK: 'క్వశ్చన్ బ్యాంక్ (PYQ) 📚',
    tool_MOCK_TEST: 'మాక్ టెస్ట్స్ ⏱️',
    tool_CUSTOM_PAPER: 'పేపర్ సింథసైజర్ 📜',
    tool_RANK_PREDICTOR: 'ర్యాంక్ ప్రిడిక్టర్ 🎯',
    tool_EXAM_TREND: 'కటాఫ్ ట్రెండ్స్ 🔮',
    tool_ANKI_FSRS: 'అంకి FSRS సింక్ 🔄',
    tool_ACADEMIC_INTEGRITY: 'అకాడమిక్ సమగ్రత 🛡️',
    tool_ANALYTICS: 'విశ్లేషణలు 📈',
    tool_AI_STUDY: 'AI స్టడీ అసిస్టెంట్ 🤖',
    tool_AI_MENTOR: 'AI మెంటార్ 🎓',
    tool_VOICE_TUTOR: 'వాయిస్ ట్యూటర్ 🎙️',
    tool_AI_PODCAST: 'AI పాడ్‌కాస్ట్ 🎙️',
    tool_SOCRATIC_DEBATE: 'డిబేట్ ఎరీనా ⚖️',
    tool_CONCEPT_GRAPH: 'కాన్సెప్ట్ గ్రాఫ్ 🕸️',
    tool_AI_WHITEBOARD: 'AI వైట్‌బోర్డ్ 🎨',
    tool_DOCUMENT_ANNOTATOR: 'పీడీఎఫ్ యానోటేటర్ 📝',
    tool_OCR_SCANNER: 'ఓసీఆర్ స్కానర్ 📷',
    tool_VIDEO_NAVIGATOR: 'వీడియో నావిగేటర్ 🎬',
    tool_SPEED_READER: 'స్పీడ్ రీడర్ ⚡',
    tool_POLYGLOT_TRANSLATOR: 'అనువాదకుడు 🌐',
    tool_SLIDE_GENERATOR: 'స్లైడ్ స్టూడియో 📊',
    tool_CAREER: 'కెరీర్ ఇంటెల్ 💼',
    tool_RESUME: 'రెజ్యూమ్ బిల్డర్ 📄',
    tool_INTERNSHIPS: 'ఇంటర్న్‌షిప్స్ 🎯',
    tool_SCHOLARSHIPS: 'స్కాలర్‌షిప్స్ 🏆',
    tool_MOCK_INTERVIEW: 'మాక్ ఇంటర్వ్యూ 🎙️',
    tool_STUDENT_FINANCES: 'ఫైనాన్స్ & బడ్జెట్ 💳',
    tool_MICRO_INTERNSHIP: 'మైక్రో-గిగ్స్ 💼',
    tool_CAMPUS_INCUBATOR: 'స్టార్టప్ ఇంక్యుబేటర్ 🚀',
    tool_FELLOWSHIP_DRAFTER: 'ఫెలోషిప్ డ్రాఫ్టర్ 🏅',
    tool_SKILL_PASSPORT: 'స్కిల్ పాస్‌పోర్ట్ 🎖️',
    tool_VENTURE_SAFE: 'వెంచర్ సేఫ్ 💼',
    tool_HFT_ORDERBOOK: 'ఆర్డర్ బుక్ 📈',
    tool_RESEARCH_LAB: 'పరిశోధనా ల్యాబ్ 🧬',
    tool_ARXIV_SCHOLAR: 'ఆర్కైవ్ స్కాలర్ 📄',
    tool_CODE_SANDBOX: 'కోడ్ శాండ్‌బాక్స్ 💻',
    tool_LATEX_STUDIO: 'లాటెక్స్ స్టూడియో 📐',
    tool_PATENT_DRAFTER: 'పేటెంట్ & ఐపీ 📜',
    tool_HOLO_SIMULATIONS: '3D హోలో ల్యాబ్ 🧬',
    tool_QUANTUM_LAB: 'క్వాంటం ల్యాబ్ ⚛️',
    tool_QUANTUM_QKD: 'క్వాంటం QKD 🔑',
    tool_LAB_NOTEBOOK: 'ల్యాబ్ నోట్‌బుక్ 🧪',
    tool_KERNEL_PROFILER: 'కెర్నల్ ప్రొఫైలర్ ⚡',
    tool_ASTRODYNAMICS: 'ఖగోళ శాస్త్రం 🪐',
    tool_CHEMICAL_RETRO: 'రసాయన సంశ్లేషణ 🧪',
    tool_SCHOLAR_TRACKER: 'స్కాలర్ ట్రాకర్ 🎓',
    tool_NEUROMORPHIC_SNN: 'న్యూరోమార్ఫిక్ SNN 🧠',
    tool_PAPER_REFEREE: 'పీర్ రివ్యూయర్ 📝',
    tool_CRISPR_EDITOR: 'జీన్ ఎడిటర్ 🧬',
    tool_FUSION_TOKAMAK: 'ఫ్యూజన్ టోకమాక్ ⚛️',
    tool_BCI_SPELLER: 'బీసీఐ స్పెల్లర్ 🧠',
    tool_LEGAL_ANALYZER: 'చట్టపరమైన విశ్లేషకుడు ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'గ్రహాల శోధన 🔭',
    tool_GRAVITATIONAL_WAVES: 'గురుత్వాకర్షణ తరంగాలు 🌌',
    tool_ROBOTICS_KINEMATICS: 'రోబోటిక్స్ 🤖',
    tool_EPIGENETIC_CLOCK: 'ఎపిజెనెటిక్ గడియారం ⏳',
    tool_COMMUNITY: 'క్యాంపస్ ఫీడ్ 👥',
    tool_LEADERBOARD: 'లీడర్‌బోర్డ్ 🏆',
    tool_STUDY_ROOMS: 'స్టడీ రూమ్స్ 🎧',
    tool_STUDY_SWARM: 'స్టడీ స్వామ్ 🤖',
    tool_QUIZ_BATTLE: 'క్విజ్ యుద్ధం ⚔️',
    tool_HACKATHON_RADAR: 'హ్యాకథాన్ రాడార్ 🏆',
    tool_HACKATHON_WAR_ROOM: 'వార్ రూమ్ ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'నాలెడ్జ్ ఒలింపియాడ్ 🏆',
    tool_FACULTY_ADVISORY: 'ఫ్యాకల్టీ సలహా 🎓',
    tool_ALUMNI_RADAR: 'పూర్వ విద్యార్థుల మెంటార్స్ 🌐',
    tool_TUTOR_BOUNTY: 'ట్యూటర్ బౌంటీ 💰',
    tool_STUDY_GUILD_DAO: 'గిల్డ్ DAO 🏛️',
    tool_CAMPUS_EXCHANGE: 'క్యాంపస్ ఎక్స్ఛేంజ్ 📦',
    tool_NOTES_MARKETPLACE: 'నోట్స్ బజార్ 🛍️',
    tool_HOSTEL_NUTRITION: 'హాస్టల్ మెస్ 🥗',
    tool_CAMPUS_TRANSIT: 'క్యాంపస్ ట్రాన్సిట్ 🚌',
    tool_CAMPUS_PRINTING: 'క్యాంపస్ ప్రింట్ 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'డిజిటల్ ట్విన్ 🗺️',
    tool_VIRTUAL_CAMPUS: '2D క్యాంపస్ 🏰',
    tool_DEADLINES: 'డెడ్‌లైన్స్ & హెచ్చరికలు 🚨',
    tool_FOCUS_GARDEN: 'ఫోకస్ గార్డెన్ 🌲',
    tool_CIRCADIAN_FOCUS: 'సిర్కాడియన్ రిథమ్ ⚡',
    tool_NEURAL_FLOW: 'న్యూరల్ ఫ్లో 🧠',
    tool_MENTAL_RESILIENCE: 'మానసిక దృఢత్వం 🧘',
    tool_ERGONOMIC_WELLNESS: 'ఎర్గోనామిక్స్ & పోస్చర్ 👁️',
    tool_CARBON_MARKET: 'కార్బన్ మార్కెట్ 🌱',

    // View Components
    phase_badge: 'దశ 53 • క్యాంపస్ రిసోర్స్ బజార్',
    verified_registry: 'ధృవీకరించబడిన విద్యార్థుల రిజిస్ట్రీ ✅',
    campus_exchange_title: 'స్మార్ట్ క్యాంపస్ పోయినవి-దొరికినవి',
    campus_exchange_title_accent: '& ఎక్విప్‌మెంట్ ఎక్స్ఛేంజ్ 🎒',
    campus_exchange_desc: 'పోయిన వస్తువులను రిపోర్ట్ చేయండి, దొరికిన ఐడీలను క్లెయిమ్ చేయండి మరియు పరికరాలను స్నేహితుల నుండి అరువు తీసుకోండి.',
    report_share_btn: '+ ఐటెమ్ రిపోర్ట్ / షేర్ చేయండి',
    filter_all: 'అన్నీ',
    filter_lost: 'పోయినవి (LOST)',
    filter_found: 'దొరికినవి (FOUND)',
    filter_borrow: 'అరువు / రెంట్ కోసం',
    search_items_placeholder: 'వస్తువు లేదా స్థలాన్ని వెతకండి...',
    badge_lost: 'పోయిన వస్తువు 🔍',
    badge_found: 'దొరికిన వస్తువు 🎁',
    badge_borrow: 'అరువు / రెంట్ 🤝',
    mark_resolved: 'పరిష్కరించబడిందిగా గుర్తించు',
    mark_borrowed: 'అరువు ఇచ్చినట్లు గుర్తించు',
    status_resolved: 'RESOLVED',
    status_claimed: 'CLAIMED',
    report_modal_title: 'పోయిన / దొరికిన వస్తువును రిపోర్ట్ చేయండి 🎒',
    field_type: 'రకం',
    field_category: 'వర్గం',
    field_title: 'వస్తువు పేరు',
    field_location: 'ప్రదేశం వివరాలు',
    field_desc: 'వివరణ & గుర్తులు',
    field_contact: 'సంప్రదింపు వివరాలు',
    btn_cancel: 'రద్దు చేయి',
    btn_publish: 'ప్రచురించు',
    opt_lost: 'పోయిన వస్తువు',
    opt_found: 'దొరికిన వస్తువు',
    opt_borrow: 'అరువు కోసం అందుబాటులో ఉంది',
    opt_calculator: 'సైంటిఫిక్ కాలిక్యులేటర్',
    opt_id_card: 'ఐడీ కార్డు / డాక్యుమెంట్',
    opt_lab_equipment: 'ల్యాబ్ పరికరాలు / టూల్స్',
    opt_book_notes: 'నోట్స్ / బుక్స్',
    opt_electronics: 'ఎలక్ట్రానిక్స్ / కేబుల్స్'
  },

  ta: {
    app_subtitle: 'படிப்பு, தேர்வுகள் மற்றும் பணிக்கான முழுமையான இயக்க முறைமை',
    cockpit: 'காக்பிட் 🚀',
    academics: 'கல்வி 📚',
    academics_full: 'கல்வி மற்றும் தேர்வுகள்',
    ai_copilot: 'AI வழிகாட்டி 🤖',
    ai_copilot_full: 'AI படிப்பு கருவிகள்',
    career: 'பணி & வாய்ப்புகள் 💼',
    career_full: 'பணி மற்றும் இன்டர்ன்ஷிப்',
    labs: 'ஆராய்ச்சி & ஆய்வகங்கள் 🔬',
    labs_full: 'டீப்டெக் மற்றும் அறிவியல் ஆய்வகங்கள்',
    community: 'வளாக மையம் 👥',
    community_full: 'சமூக அரங்கம்',
    campus: 'வளாகம் & நல்வாழ்வு 🏫',
    campus_full: 'வளாக வாழ்க்கை மற்றும் ஆரோக்கியம்',
    grandmaster: 'கிராண்ட்மாஸ்டர் 👑',
    roadmap: 'திட்ட வரைபடம் 🗺️',
    search: 'தேடுங்கள்',
    api_online: 'ஆன்லைன் ✅',
    api_standby: 'காத்திருப்பு',
    daily_digest: 'தினசரி சுருக்கம் ☀️',
    sign_in: 'உள்நுழைக',
    sign_out: 'வெளியேறு',
    level_scholar: 'நிலை {level} அறிஞர் 🎓',
    total_xp: 'மொத்த எக்ஸ்பி',
    xp_needed: 'தேவைப்படும் எக்ஸ்பி',
    day_streak: 'தொடர் நாட்கள் 🔥',
    edit_profile: 'சுயவிவரம் திருத்து',
    daily_study_target: 'தினசரி படிப்பு இலக்கு ⏱️',
    target_exams: 'இலக்கு தேர்வுகள் 🎯',
    dream_career: 'கனவுப் பணி 💼',
    skills: 'திறன்கள்',
    smart_focus_engine: 'ஸ்மார்ட் கவன இயந்திரம் ⏱️',
    pomodoro_protocol: 'போமோடோரோ தீவிர படிப்பு நெறிமுறை',
    focus_25: '25 நிமிட கவனம்',
    focus_50: '50 நிமிட ஆழ்ந்த படிப்பு',
    break_5: '5 நிமிட இடைவேளை',
    study_commitment: 'இன்றைய படிப்பு முன்னேற்றம்',
    daily_telemetry: 'தினசரி இலக்கு டிராக்கர்',
    time_studied_today: 'இன்று படித்த நேரம்:',
    target_label: 'இலக்கு:',
    remaining_label: 'மீதமுள்ள நேரம்:',
    target_exam_countdowns: 'தேர்வு கவுண்டவுன் ⏳',
    milestone_tracker: 'வரவிருக்கும் தேர்வு அட்டவணை',
    view_prep_hub: 'பயிற்சி மையத்தைக் காண்க',
    days_left: 'நாட்கள் மீதமுள்ளன',
    spaced_repetition_queue: 'நினைவூட்டல் வரிசை (SM-2) 🧠',
    memory_curve: 'நினைவாற்றல் வளைவு',
    start_rapid_review: 'மறுபார்வை தொடங்கு ⚡',
    due_today: 'கார்டுகள் மறுபார்வைக்கு உள்ளன',
    estimated_time: 'மதிப்பிடப்பட்ட நேரம்',
    ai_shortcuts_title: 'AI படிப்பு குறுக்குவழிகள் 🤖✨',
    ai_shortcuts_sub: 'உடனடி AI கருவிகள்',
    summarize_notes: 'குறிப்புகளின் சுருக்கம்',
    generate_flashcards: 'ஃபிளாஷ்கார்டுகளை உருவாக்கு',
    ask_ai_mentor: 'AI வழிகாட்டியிடம் கேளுங்கள்',
    quote_text: '"விடாமுயற்சியும் தொடர் ஒழுக்கமும் மகத்தான வெற்றியைத் தரும்."',
    quote_author: '— ஊக்கமளிக்கும் சிந்தனை',
    live_telemetry: 'நேரலை டெலிமெட்ரி 📡',
    streaming: 'ஸ்ட்ரீமிங் 🟢',
    paused: 'நிறுத்தப்பட்டது ⏸️',
    footer_text: 'StudentLife OS 16.0 (கிராண்ட்மாஸ்டர் பதிப்பு) • 100/100 நிலைகள் முழுமையாக செயல்படுகின்றன 🏆💯',

    // Tools
    tool_PLANNER: 'படிப்பு திட்டமிடுபவர் 📅',
    tool_SYLLABUS: 'பாடத்திட்ட டிராக்கர் 🌲',
    tool_NOTES: 'குறிப்புகள் மையம் 📝',
    tool_REVISION: 'மறுபார்வை இயந்திரம் 🧠',
    tool_EXAM_PREP: 'தேர்வு தயாரிப்பு 🎯',
    tool_QUESTION_BANK: 'வினா வங்கி 📚',
    tool_MOCK_TEST: 'மாதிரி தேர்வுகள் ⏱️',
    tool_CUSTOM_PAPER: 'வினாத்தாள் ஜெனரேட்டர் 📜',
    tool_RANK_PREDICTOR: 'ரேங்க் கணிப்பாளர் 🎯',
    tool_EXAM_TREND: 'கட்ஆஃப் போக்குகள் 🔮',
    tool_ANKI_FSRS: 'அங்கி FSRS ஒத்திசைவு 🔄',
    tool_ACADEMIC_INTEGRITY: 'கல்வி ஒருமைப்பாடு 🛡️',
    tool_ANALYTICS: 'செயல்திறன் பகுப்பாய்வு 📈',
    tool_AI_STUDY: 'AI படிப்பு உதவியாளர் 🤖',
    tool_AI_MENTOR: 'AI வழிகாட்டி 🎓',
    tool_VOICE_TUTOR: 'குரல் ஆசிரியர் 🎙️',
    tool_AI_PODCAST: 'AI போட்காஸ்ட் 🎙️',
    tool_SOCRATIC_DEBATE: 'விவாத அரங்கம் ⚖️',
    tool_CONCEPT_GRAPH: 'கருத்து வரைபடம் 🕸️',
    tool_AI_WHITEBOARD: 'AI ஒயிட்போர்டு 🎨',
    tool_DOCUMENT_ANNOTATOR: 'PDF குறிப்பான் 📝',
    tool_OCR_SCANNER: 'OCR ஸ்கேனர் 📷',
    tool_VIDEO_NAVIGATOR: 'வீடியோ வழிகாட்டி 🎬',
    tool_SPEED_READER: 'வேக வாசிப்பான் ⚡',
    tool_POLYGLOT_TRANSLATOR: 'மொழிபெயர்ப்பாளர் 🌐',
    tool_SLIDE_GENERATOR: 'ஸ்லைடு ஸ்டுடியோ 📊',
    tool_CAREER: 'பணி வழிகாட்டல் 💼',
    tool_RESUME: 'ரெஸ்யூம் பில்டர் 📄',
    tool_INTERNSHIPS: 'இன்டர்ன்ஷிப் 🎯',
    tool_SCHOLARSHIPS: 'கல்வி உதவித்தொகை 🏆',
    tool_MOCK_INTERVIEW: 'மாதிரி நேர்காணல் 🎙️',
    tool_STUDENT_FINANCES: 'நிதி & பட்ஜெட் 💳',
    tool_MICRO_INTERNSHIP: 'மைக்ரோ-கிக்ஸ் 💼',
    tool_CAMPUS_INCUBATOR: 'தொழில் தொடக்க மையம் 🚀',
    tool_FELLOWSHIP_DRAFTER: 'ஃபெலோஷிப் வரைவு 🏅',
    tool_SKILL_PASSPORT: 'திறன் பாஸ்போர்ட் 🎖️',
    tool_VENTURE_SAFE: 'வென்ச்சர் சேஃப் 💼',
    tool_HFT_ORDERBOOK: 'ஆர்டர் புக் 📈',
    tool_RESEARCH_LAB: 'ஆராய்ச்சி ஆய்வகம் 🧬',
    tool_ARXIV_SCHOLAR: 'ஆர்க்கைவ் ஸ்காலர் 📄',
    tool_CODE_SANDBOX: 'கோட் சாண்ட்பாக்ஸ் 💻',
    tool_LATEX_STUDIO: 'லேடெக்ஸ் ஸ்டுடியோ 📐',
    tool_PATENT_DRAFTER: 'காப்புரிமை வரைவு 📜',
    tool_HOLO_SIMULATIONS: '3D ஹோலோ ஆய்வகம் 🧬',
    tool_QUANTUM_LAB: 'குவாண்டம் ஆய்வகம் ⚛️',
    tool_QUANTUM_QKD: 'குவாண்டம் QKD 🔑',
    tool_LAB_NOTEBOOK: 'ஆய்வக நோட்புக் 🧪',
    tool_KERNEL_PROFILER: 'கர்னல் புரொஃபைலர் ⚡',
    tool_ASTRODYNAMICS: 'வானியற்பியல் 🪐',
    tool_CHEMICAL_RETRO: 'வேதியியல் சேர்க்கை 🧪',
    tool_SCHOLAR_TRACKER: 'ஸ்காலர் டிராக்கர் 🎓',
    tool_NEUROMORPHIC_SNN: 'நியூரோமார்பிக் SNN 🧠',
    tool_PAPER_REFEREE: 'மதிப்பாய்வாளர் 📝',
    tool_CRISPR_EDITOR: 'மரபணு திருத்தி 🧬',
    tool_FUSION_TOKAMAK: 'ஃப்யூஷன் டோகாமாக் ⚛️',
    tool_BCI_SPELLER: 'பிசிஐ ஸ்பெல்லர் 🧠',
    tool_LEGAL_ANALYZER: 'சட்ட பகுப்பாய்வாளர் ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'புறக்கோள் ஆய்வு 🔭',
    tool_GRAVITATIONAL_WAVES: 'ஈர்ப்பு அலைகள் 🌌',
    tool_ROBOTICS_KINEMATICS: 'ரோபாட்டிக்ஸ் 🤖',
    tool_EPIGENETIC_CLOCK: 'எபிஜெனெடிக் கடிகாரம் ⏳',
    tool_COMMUNITY: 'வளாக அரங்கம் 👥',
    tool_LEADERBOARD: 'முன்னிலை பலகை 🏆',
    tool_STUDY_ROOMS: 'படிப்பு அறைகள் 🎧',
    tool_STUDY_SWARM: 'கூட்டுப் படிப்பு 🤖',
    tool_QUIZ_BATTLE: 'வினாடி வினா அரங்கம் ⚔️',
    tool_HACKATHON_RADAR: 'ஹேக்கத்தான் ராடார் 🏆',
    tool_HACKATHON_WAR_ROOM: 'வார் ரூம் ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'அறிவு ஒலிம்பியாட் 🏆',
    tool_FACULTY_ADVISORY: 'ஆசிரிய ஆலோசனை 🎓',
    tool_ALUMNI_RADAR: 'முன்னாள் மாணவர் வழிகாட்டிகள் 🌐',
    tool_TUTOR_BOUNTY: 'டியூட்டர் பவுண்டி 💰',
    tool_STUDY_GUILD_DAO: 'கில்ட் DAO 🏛️',
    tool_CAMPUS_EXCHANGE: 'வளாக பரிமாற்றம் 📦',
    tool_NOTES_MARKETPLACE: 'குறிப்புகள் சந்தை 🛍️',
    tool_HOSTEL_NUTRITION: 'விடுதி உணவகம் 🥗',
    tool_CAMPUS_TRANSIT: 'வளாக போக்குவரத்து 🚌',
    tool_CAMPUS_PRINTING: 'வளாக அச்சுப்பணி 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'டிஜிட்டல் இரட்டை 🗺️',
    tool_VIRTUAL_CAMPUS: '2D வளாகம் 🏰',
    tool_DEADLINES: 'கடைசி தேதிகள் & விழிப்பூட்டல்கள் 🚨',
    tool_FOCUS_GARDEN: 'கவன தோட்டம் 🌲',
    tool_CIRCADIAN_FOCUS: 'உயிரியல் கடிகாரம் ⚡',
    tool_NEURAL_FLOW: 'நியூரல் ஃப்ளோ 🧠',
    tool_MENTAL_RESILIENCE: 'மன நலம் 🧘',
    tool_ERGONOMIC_WELLNESS: 'உடல் தோரணை ஆரோக்கியம் 👁️',
    tool_CARBON_MARKET: 'கார்பன் சந்தை 🌱',

    // View Components
    phase_badge: 'கட்டம் 53 • வளாக வள சந்தை',
    verified_registry: 'சரிபார்க்கப்பட்ட மாணவர் பதிவேடு ✅',
    campus_exchange_title: 'ஸ்மார்ட் வளாக தொலைந்தவை-கிடைத்தவை',
    campus_exchange_title_accent: '& உபகரண பரிமாற்றம் 🎒',
    campus_exchange_desc: 'தொலைந்த பொருட்களைப் புகாரளிக்கவும், அடையாள அட்டைகளைக் கோரவும், தோழர்களிடமிருந்து உபகரணங்களை இரவல் பெறவும்.',
    report_share_btn: '+ பொருளைப் பதிவு செய் / பகிர்',
    filter_all: 'அனைத்தும்',
    filter_lost: 'தொலைந்தது (LOST)',
    filter_found: 'கிடைத்தது (FOUND)',
    filter_borrow: 'இரவல் / வாடகைக்கு',
    search_items_placeholder: 'பொருள் அல்லது இடத்தை தேடுங்கள்...',
    badge_lost: 'தொலைந்த பொருள் 🔍',
    badge_found: 'கிடைத்த பொருள் 🎁',
    badge_borrow: 'இரவல் / பகிர்வு 🤝',
    mark_resolved: 'தீர்க்கப்பட்டது என குறிக்கவும்',
    mark_borrowed: 'இரவல் வழங்கப்பட்டது',
    status_resolved: 'RESOLVED',
    status_claimed: 'CLAIMED',
    report_modal_title: 'பொருளைப் புகாரளிக்கவும் அல்லது பகிரவும் 🎒',
    field_type: 'வகை',
    field_category: 'பிரிவு',
    field_title: 'பொருளின் பெயர்',
    field_location: 'இட விவரங்கள்',
    field_desc: 'விளக்கம் & அடையாளங்கள்',
    field_contact: 'தொடர்பு விவரம்',
    btn_cancel: 'ரத்து செய்',
    btn_publish: 'வெளியிடு',
    opt_lost: 'தொலைந்த பொருள்',
    opt_found: 'கிடைத்த பொருள்',
    opt_borrow: 'இரவலுக்கு கிடைப்பது',
    opt_calculator: 'அறிவியல் கால்குலேட்டர்',
    opt_id_card: 'அடையாள அட்டை / ஆவணம்',
    opt_lab_equipment: 'ஆய்வக கருவிகள்',
    opt_book_notes: 'குறிப்புகள் / புத்தகம்',
    opt_electronics: 'எலக்ட்ரானிக்ஸ் / கேபிள்கள்'
  },

  mr: {
    app_subtitle: 'अभ्यास, परीक्षा आणि करिअरसाठी संपूर्ण ऑपरेटिंग सिस्टम',
    cockpit: 'कॉकपिट 🚀',
    academics: 'शैक्षणिक 📚',
    academics_full: 'शैक्षणिक आणि परीक्षा केंद्र',
    ai_copilot: 'AI सह-पायलट 🤖',
    ai_copilot_full: 'AI अभ्यास साधने व स्टुडिओ',
    career: 'करिअर आणि संधी 💼',
    career_full: 'करिअर, रेझ्युमे आणि इंटर्नशिप',
    labs: 'संशोधन व प्रयोगशाळा 🔬',
    labs_full: 'डीपटेक आणि विज्ञान लॅब',
    community: 'कॅम्पस हब 👥',
    community_full: 'समुदाय व अभ्यास कक्ष',
    campus: 'कॅम्पस आणि आरोग्य 🏫',
    campus_full: 'कॅम्पस जीवन आणि स्वास्थ्य',
    grandmaster: 'ग्रँडमास्टर 👑',
    roadmap: 'रोडमॅप 🗺️',
    search: 'शोधा',
    api_online: 'ऑनलाइन ✅',
    api_standby: 'स्टँडबाय',
    daily_digest: 'दैनिक डायजेस्ट ☀️',
    sign_in: 'साइन इन / लॉगिन',
    sign_out: 'लॉग आउट',
    level_scholar: 'पातळी {level} विद्वान 🎓',
    total_xp: 'एकूण XP',
    xp_needed: 'पुढील पातळीसाठी XP',
    day_streak: 'सलग दिवस 🔥',
    edit_profile: 'प्रोफाइल संपादित करा',
    daily_study_target: 'दैनिक अभ्यास लक्ष्य ⏱️',
    target_exams: 'लक्ष्य परीक्षा 🎯',
    dream_career: 'स्वप्नातील करिअर 💼',
    skills: 'कौशल्ये',
    smart_focus_engine: 'स्मार्ट फोकस इंजिन ⏱️',
    pomodoro_protocol: 'पोमोडोरो डीप वर्क प्रोटोकॉल',
    focus_25: '२५ मिनिटे एकाग्रता',
    focus_50: '५० मिनिटे सखोल अभ्यास',
    break_5: '५ मिनिटे विश्रांती',
    study_commitment: 'आजचा अभ्यास संकल्प',
    daily_telemetry: 'दैनिक प्रगती ट्रॅकर',
    time_studied_today: 'आज केलेला अभ्यास वेळ:',
    target_label: 'लक्ष्य:',
    remaining_label: 'उरलेला वेळ:',
    target_exam_countdowns: 'परीक्षा रिव्हर्स काउंटडाउन ⏳',
    milestone_tracker: 'आगामी परीक्षा वेळापत्रक',
    view_prep_hub: 'तयारी केंद्र पहा',
    days_left: 'दिवस शिल्लक',
    spaced_repetition_queue: 'पुनरावृत्ती रांग (SM-2) 🧠',
    memory_curve: 'स्मृती धारणा आलेख',
    start_rapid_review: 'रिव्हिजन सुरू करा ⚡',
    due_today: 'कार्ड्स आज पुनरावृत्तीसाठी बाकी आहेत',
    estimated_time: 'अंदाजे वेळ',
    ai_shortcuts_title: 'AI अभ्यास शॉर्टकट्स 🤖✨',
    ai_shortcuts_sub: 'त्वरित संदर्भ AI साधने',
    summarize_notes: 'नोट्सचा सारांश बनवा',
    generate_flashcards: 'फ्लॅशकार्ड्स तयार करा',
    ask_ai_mentor: 'AI मार्गदर्शकाला विचारा',
    quote_text: '"दररोजचा सराव आणि सातत्य यामुळेच मोठे यश मिळते."',
    quote_author: '— प्रेरणादायी विचार',
    live_telemetry: 'थेट टेलिमेट्री 📡',
    streaming: 'स्ट्रीमिंग 🟢',
    paused: 'थांबवले ⏸️',
    footer_text: 'StudentLife OS 16.0 (ग्रँडमास्टर आवृत्ती) • १००/१०० टप्पे पूर्णतः कार्यरत 🏆💯',

    // Tools
    tool_PLANNER: 'अभ्यास नियोजक 📅',
    tool_SYLLABUS: 'अभ्यासक्रम ट्रॅकर 🌲',
    tool_NOTES: 'नोट्स हब 📝',
    tool_REVISION: 'स्मृती पुनरावृत्ती 🧠',
    tool_EXAM_PREP: 'परीक्षा तयारी 🎯',
    tool_QUESTION_BANK: 'प्रश्न संच (PYQ) 📚',
    tool_MOCK_TEST: 'सराव परीक्षा ⏱️',
    tool_CUSTOM_PAPER: 'प्रश्नपत्रिका निर्माता 📜',
    tool_RANK_PREDICTOR: 'रँक प्रेडिक्टर 🎯',
    tool_EXAM_TREND: 'कटऑफ ट्रेंड्स 🔮',
    tool_ANKI_FSRS: 'अंकी FSRS सिंक 🔄',
    tool_ACADEMIC_INTEGRITY: 'अकादमिक सुरक्षा 🛡️',
    tool_ANALYTICS: 'कामगिरी विश्लेषण 📈',
    tool_AI_STUDY: 'AI अभ्यास सहाय्यक 🤖',
    tool_AI_MENTOR: 'AI मार्गदर्शक 🎓',
    tool_VOICE_TUTOR: 'व्हॉइस ट्यूटर 🎙️',
    tool_AI_PODCAST: 'AI पॉडकास्ट 🎙️',
    tool_SOCRATIC_DEBATE: 'वादविवाद मंच ⚖️',
    tool_CONCEPT_GRAPH: 'माइंड मॅप ग्राफ 🕸️',
    tool_AI_WHITEBOARD: 'AI व्हाईटबोर्ड 🎨',
    tool_DOCUMENT_ANNOTATOR: 'पीडीएफ एनोटेटर 📝',
    tool_OCR_SCANNER: 'ओसीआर स्कॅनर 📷',
    tool_VIDEO_NAVIGATOR: 'व्हिडिओ नेव्हिगेटर 🎬',
    tool_SPEED_READER: 'स्पीड रीडर ⚡',
    tool_POLYGLOT_TRANSLATOR: 'भाषांतरकार 🌐',
    tool_SLIDE_GENERATOR: 'स्लाइड स्टुडिओ 📊',
    tool_CAREER: 'करिअर मार्गदर्शन 💼',
    tool_RESUME: 'रेझ्युमे बिल्डर 📄',
    tool_INTERNSHIPS: 'इंटर्नशिप पोर्टल 🎯',
    tool_SCHOLARSHIPS: 'शिष्यवृत्ती शोधक 🏆',
    tool_MOCK_INTERVIEW: 'मॉक मुलाखत 🎙️',
    tool_STUDENT_FINANCES: 'विद्यार्थी वित्त व बजेट 💳',
    tool_MICRO_INTERNSHIP: 'मायक्रो-गिग्स 💼',
    tool_CAMPUS_INCUBATOR: 'स्टार्टअप इनक्युबेटर 🚀',
    tool_FELLOWSHIP_DRAFTER: 'फेलोशिप ड्राफ्टर 🏅',
    tool_SKILL_PASSPORT: 'कौशल्य पासपोर्ट 🎖️',
    tool_VENTURE_SAFE: 'व्हेंचर सेफ 💼',
    tool_HFT_ORDERBOOK: 'ऑर्डर बुक 📈',
    tool_RESEARCH_LAB: 'संशोधन लॅब 🧬',
    tool_ARXIV_SCHOLAR: 'आर्काइव्ह स्कॉलर 📄',
    tool_CODE_SANDBOX: 'कोड सँडबॉक्स 💻',
    tool_LATEX_STUDIO: 'लाटेक्स स्टुडिओ 📐',
    tool_PATENT_DRAFTER: 'पेटंट व आयपी 📜',
    tool_HOLO_SIMULATIONS: '3D होलो-लॅब 🧬',
    tool_QUANTUM_LAB: 'क्वांटम लॅब ⚛️',
    tool_QUANTUM_QKD: 'क्वांटम QKD 🔑',
    tool_LAB_NOTEBOOK: 'लॅब नोटबुक 🧪',
    tool_KERNEL_PROFILER: 'कर्नेल प्रोफाइलर ⚡',
    tool_ASTRODYNAMICS: 'खगोलशास्त्र सिम्युलेटर 🪐',
    tool_CHEMICAL_RETRO: 'रासायनिक संश्लेषण 🧪',
    tool_SCHOLAR_TRACKER: 'विद्वान ट्रॅकर 🎓',
    tool_NEUROMORPHIC_SNN: 'न्यूरोमॉर्फिक SNN 🧠',
    tool_PAPER_REFEREE: 'सहकारी समीक्षक 📝',
    tool_CRISPR_EDITOR: 'जीन एडिटर 🧬',
    tool_FUSION_TOKAMAK: 'फ्यूजन टोकामाक ⚛️',
    tool_BCI_SPELLER: 'बीसीआय स्पेलर 🧠',
    tool_LEGAL_ANALYZER: 'कायदेशीर विश्लेषक ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'ग्रह शोध 🔭',
    tool_GRAVITATIONAL_WAVES: 'गुरुत्वाकर्षण लहरी 🌌',
    tool_ROBOTICS_KINEMATICS: 'रोबोटिक्स 🤖',
    tool_EPIGENETIC_CLOCK: 'एपिजेनेटिक घड्याळ ⏳',
    tool_COMMUNITY: 'कॅम्पस समुदाय 👥',
    tool_LEADERBOARD: 'लीडरबोर्ड 🏆',
    tool_STUDY_ROOMS: 'अभ्यास कक्ष 🎧',
    tool_STUDY_SWARM: 'अभ्यास झुंड 🤖',
    tool_QUIZ_BATTLE: 'क्विझ अखाडा ⚔️',
    tool_HACKATHON_RADAR: 'हॅकाथॉन रडार 🏆',
    tool_HACKATHON_WAR_ROOM: 'वॉर रूम ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'ज्ञान ऑलिम्पियाड 🏆',
    tool_FACULTY_ADVISORY: 'प्राध्यापक सल्ला 🎓',
    tool_ALUMNI_RADAR: 'माजी विद्यार्थी मार्गदर्शक 🌐',
    tool_TUTOR_BOUNTY: 'ट्यूटर बाउंटी 💰',
    tool_STUDY_GUILD_DAO: 'गिल्ड DAO 🏛️',
    tool_CAMPUS_EXCHANGE: 'कॅम्पस एक्सचेंज 📦',
    tool_NOTES_MARKETPLACE: 'नोट्स बाजार 🛍️',
    tool_HOSTEL_NUTRITION: 'हॉस्टेल मेस 🥗',
    tool_CAMPUS_TRANSIT: 'कॅम्पस वाहतूक 🚌',
    tool_CAMPUS_PRINTING: 'कॅम्पस प्रिंट 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'डिजिटल ट्विन 🗺️',
    tool_VIRTUAL_CAMPUS: '२डी कॅम्पस 🏰',
    tool_DEADLINES: 'मुदत व सूचना 🚨',
    tool_FOCUS_GARDEN: 'फोकस गार्डन 🌲',
    tool_CIRCADIAN_FOCUS: 'सर्केडियन रिदम ⚡',
    tool_NEURAL_FLOW: 'न्यूरल फ्लो 🧠',
    tool_MENTAL_RESILIENCE: 'मानसिक स्वास्थ्य 🧘',
    tool_ERGONOMIC_WELLNESS: 'शारीरिक मुद्रा व आरोग्य 👁️',
    tool_CARBON_MARKET: 'कार्बन मार्केट 🌱',

    // View components
    phase_badge: 'टप्पा ५३ • कॅम्पस संसाधन बाजार',
    verified_registry: 'सत्यापित विद्यार्थी नोंदणी ✅',
    campus_exchange_title: 'स्मार्ट कॅम्पस हरवले-सापडले',
    campus_exchange_title_accent: 'व साहित्य विनिमय 🎒',
    campus_exchange_desc: 'हरवलेल्या वस्तूंची तक्रार करा, मिळालेली ओळखपत्रे व कॅल्क्युलेटर मिळवा आणि सहकाऱ्यांकडून साहित्य उसने घ्या.',
    report_share_btn: '+ वस्तू नोंदवा / शेअर करा',
    filter_all: 'सर्व',
    filter_lost: 'हरवले (LOST)',
    filter_found: 'सापडले (FOUND)',
    filter_borrow: 'उसने / भाड्याने',
    search_items_placeholder: 'वस्तू किंवा ठिकाण शोधा...',
    badge_lost: 'हरवलेली वस्तू 🔍',
    badge_found: 'सापडलेली वस्तू 🎁',
    badge_borrow: 'उसने / भाड्याने 🤝',
    mark_resolved: 'निकाली काढले नोंदवा',
    mark_borrowed: 'उसने दिले नोंदवा',
    status_resolved: 'RESOLVED',
    status_claimed: 'CLAIMED',
    report_modal_title: 'हरवलेली / सापडलेली वस्तू नोंदवा 🎒',
    field_type: 'प्रकार',
    field_category: 'श्रेणी',
    field_title: 'वस्तूचे नाव',
    field_location: 'ठिकाण तपशील',
    field_desc: 'वर्णन व ओळख',
    field_contact: 'संपर्क माहिती',
    btn_cancel: 'रद्द करा',
    btn_publish: 'प्रसिद्ध करा',
    opt_lost: 'हरवलेली वस्तू',
    opt_found: 'सापडलेली वस्तू',
    opt_borrow: 'उसने देण्यासाठी उपलब्ध',
    opt_calculator: 'वैज्ञानिक कॅल्क्युलेटर',
    opt_id_card: 'ओळखपत्र / कागदपत्रे',
    opt_lab_equipment: 'लॅब साधने / टूल्स',
    opt_book_notes: 'नोट्स / पुस्तके',
    opt_electronics: 'इलेक्ट्रॉनिक्स / केबल्स'
  },

  gu: {
    app_subtitle: 'અભ્યાસ, પરીક્ષા અને કારકિર્દી માટે સંપૂર્ણ ઓપરેટિંગ સિસ્ટમ',
    cockpit: 'કોકપિટ 🚀',
    academics: 'શૈક્ષણિક 📚',
    academics_full: 'શૈક્ષણિક અને પરીક્ષાઓ',
    ai_copilot: 'AI કોપાયલટ 🤖',
    ai_copilot_full: 'AI અભ્યાસ સાધનો',
    career: 'કારકિર્દી અને તકો 💼',
    career_full: 'કારકિર્દી અને ઇન્ટર્નશીપ',
    labs: 'સંશોધન અને લેબ્સ 🔬',
    labs_full: 'ડીપટેક અને વિજ્ઞાન લેબ્સ',
    community: 'કેમ્પસ હબ 👥',
    community_full: 'સમુદાય અને અખાડો',
    campus: 'કેમ્પસ અને આરોગ્ય 🏫',
    campus_full: 'કેમ્પસ જીવન અને સુખાકારી',
    grandmaster: 'ગ્રાન્ડમાસ્ટર 👑',
    roadmap: 'રોડમેપ 🗺️',
    search: 'શોધો',
    api_online: 'ઓનલાઈન ✅',
    api_standby: 'સ્ટેન્ડબાય',
    daily_digest: 'દૈનિક ડાયજેસ્ટ ☀️',
    sign_in: 'સાઇન ઇન / લૉગિન',
    sign_out: 'લૉગ આઉટ',
    level_scholar: 'લેવલ {level} વિદ્વાન 🎓',
    total_xp: 'કુલ XP',
    xp_needed: 'આગલા લેવલ માટે XP',
    day_streak: 'દિવસોની સ્ટ્રીક 🔥',
    edit_profile: 'પ્રોફાઇલ બદલો',
    daily_study_target: 'દૈનિક અભ્યાસ લક્ષ્ય ⏱️',
    target_exams: 'લક્ષ્ય પરીક્ષાઓ 🎯',
    dream_career: 'ડ્રીમ કારકિર્દી 💼',
    skills: 'કૌશલ્યો',
    smart_focus_engine: 'સ્માર્ટ ફોકસ એન્જિન ⏱️',
    pomodoro_protocol: 'પોમોડોરો ડીપ વર્ક પ્રોટોકોલ',
    focus_25: '25 મિનિટ એકાગ્રતા',
    focus_50: '50 મિનિટ ઊંડો અભ્યાસ',
    break_5: '5 મિનિટ વિરામ',
    study_commitment: 'આજનો અભ્યાસ સંકલ્પ',
    daily_telemetry: 'દૈનિક પ્રગતિ ટ્રેકર',
    time_studied_today: 'આજે કરેલ અભ્યાસ સમય:',
    target_label: 'લક્ષ્ય:',
    remaining_label: 'બાકી સમય:',
    target_exam_countdowns: 'પરીક્ષા કાઉન્ટડાઉન ⏳',
    milestone_tracker: 'આગામી પરીક્ષાઓનું કાઉન્ટડાઉન',
    view_prep_hub: 'તૈયારી કેન્દ્ર જુઓ',
    days_left: 'દિવસો બાકી',
    spaced_repetition_queue: 'પુનરાવર્તન કતાર (SM-2) 🧠',
    memory_curve: 'મેમરી રીટેન્શન કર્વ',
    start_rapid_review: 'રિવિઝન શરૂ કરો ⚡',
    due_today: 'કાર્ડ આજે પુનરાવર્તન માટે બાકી છે',
    estimated_time: 'અંદાજિત સમય',
    ai_shortcuts_title: 'AI અભ્યાસ શોર્ટકટ્સ 🤖✨',
    ai_shortcuts_sub: 'ઝડપી AI સહાયક સાધનો',
    summarize_notes: 'નોટ્સનો સારાંશ બનાવો',
    generate_flashcards: 'ફ્લેશકાર્ડ્સ બનાવો',
    ask_ai_mentor: 'AI મેન્ટરને પૂછો',
    quote_text: '"નિયમિત મહેનત અને શિસ્ત જ મહાન સફળતા અપાવે છે."',
    quote_author: '— પ્રેરણાદાયી વિચાર',
    live_telemetry: 'લાઇવ ટેલિમેટ્રી 📡',
    streaming: 'સ્ટ્રીમિંગ 🟢',
    paused: 'અટકાવેલ ⏸️',
    footer_text: 'StudentLife OS 16.0 (ગ્રાન્ડમાસ્ટર સંસ્કરણ) • 100/100 તબક્કા સંપૂર્ણ સક્રિય 🏆💯',

    // Tools
    tool_PLANNER: 'અભ્યાસ આયોજક 📅',
    tool_SYLLABUS: 'અભ્યાસક્રમ ટ્રેકર 🌲',
    tool_NOTES: 'નોટ્સ હબ 📝',
    tool_REVISION: 'રિવિઝન એન્જિન 🧠',
    tool_EXAM_PREP: 'પરીક્ષા તૈયારી 🎯',
    tool_QUESTION_BANK: 'પ્રશ્ન બેંક (PYQ) 📚',
    tool_MOCK_TEST: 'મોક ટેસ્ટ ⏱️',
    tool_CUSTOM_PAPER: 'પેપર જનરેટર 📜',
    tool_RANK_PREDICTOR: 'રેન્ક પ્રિડિક્ટર 🎯',
    tool_EXAM_TREND: 'કટઓફ ટ્રેન્ડ્સ 🔮',
    tool_ANKI_FSRS: 'અંકી FSRS સિંક 🔄',
    tool_ACADEMIC_INTEGRITY: 'શૈક્ષણિક સુરક્ષા 🛡️',
    tool_ANALYTICS: 'વિશ્લેષણ 📈',
    tool_AI_STUDY: 'AI અભ્યાસ સહાયક 🤖',
    tool_AI_MENTOR: 'AI મેન્ટર 🎓',
    tool_VOICE_TUTOR: 'વોઇસ ટ્યુટર 🎙️',
    tool_AI_PODCAST: 'AI પોડકાસ્ટ 🎙️',
    tool_SOCRATIC_DEBATE: 'ચર્ચા મંચ ⚖️',
    tool_CONCEPT_GRAPH: 'કન્સેપ્ટ ગ્રાફ 🕸️',
    tool_AI_WHITEBOARD: 'AI વ્હાઇટબોર્ડ 🎨',
    tool_DOCUMENT_ANNOTATOR: 'પીડીએફ એનોટેટર 📝',
    tool_OCR_SCANNER: 'ઓસીઆર સ્કેનર 📷',
    tool_VIDEO_NAVIGATOR: 'વિડિઓ નેવિગેટર 🎬',
    tool_SPEED_READER: 'સ્પીડ રીડર ⚡',
    tool_POLYGLOT_TRANSLATOR: 'અનુવાદક 🌐',
    tool_SLIDE_GENERATOR: 'સ્લાઇડ સ્ટુડિયો 📊',
    tool_CAREER: 'કારકિર્દી માર્ગદર્શન 💼',
    tool_RESUME: 'રેઝ્યુમે બિલ્ડર 📄',
    tool_INTERNSHIPS: 'ઇન્ટર્નશીપ 🎯',
    tool_SCHOLARSHIPS: 'સ્કોલરશીપ શોધક 🏆',
    tool_MOCK_INTERVIEW: 'મોક ઇન્ટરવ્યુ 🎙️',
    tool_STUDENT_FINANCES: 'નાણાં અને બજેટ 💳',
    tool_MICRO_INTERNSHIP: 'માઇક્રો-ગિગ્સ 💼',
    tool_CAMPUS_INCUBATOR: 'સ્ટાર્ટઅપ ઇન્ક્યુબેટર 🚀',
    tool_FELLOWSHIP_DRAFTER: 'ફેલોશિપ ડ્રાફ્ટર 🏅',
    tool_SKILL_PASSPORT: 'સ્કિલ પાસપોર્ટ 🎖️',
    tool_VENTURE_SAFE: 'વેન્ચર સેફ 💼',
    tool_HFT_ORDERBOOK: 'ઓર્ડર બુક 📈',
    tool_RESEARCH_LAB: 'સંશોધન લેબ 🧬',
    tool_ARXIV_SCHOLAR: 'આર્કાઇવ સ્કોલર 📄',
    tool_CODE_SANDBOX: 'કોડ સેન્ડબોક્સ 💻',
    tool_LATEX_STUDIO: 'લાટેક્સ સ્ટુડિયો 📐',
    tool_PATENT_DRAFTER: 'પેટન્ટ અને આઇપી 📜',
    tool_HOLO_SIMULATIONS: '3D હોલો લેબ 🧬',
    tool_QUANTUM_LAB: 'ક્વોન્ટમ લેબ ⚛️',
    tool_QUANTUM_QKD: 'ક્વોન્ટમ QKD 🔑',
    tool_LAB_NOTEBOOK: 'લેબ નોટબુક 🧪',
    tool_KERNEL_PROFILER: 'કર્નલ પ્રોફાઇલર ⚡',
    tool_ASTRODYNAMICS: 'ખગોળશાસ્ત્ર સિમ્યુલેટર 🪐',
    tool_CHEMICAL_RETRO: 'રાસાયણિક સંશ્લેષણ 🧪',
    tool_SCHOLAR_TRACKER: 'સ્કોલર ટ્રેકર 🎓',
    tool_NEUROMORPHIC_SNN: 'ન્યુરોમોર્ફિક SNN 🧠',
    tool_PAPER_REFEREE: 'સમીક્ષક 📝',
    tool_CRISPR_EDITOR: 'જીન એડિટર 🧬',
    tool_FUSION_TOKAMAK: 'ફ્યુઝન ટોકામેક ⚛️',
    tool_BCI_SPELLER: 'બીસીઆઈ સ્પેલર 🧠',
    tool_LEGAL_ANALYZER: 'કાનૂની વિશ્લેષક ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'ગ્રહ શોધ 🔭',
    tool_GRAVITATIONAL_WAVES: 'ગુરુત્વાકર્ષણ તરંગો 🌌',
    tool_ROBOTICS_KINEMATICS: 'રોબોટિક્સ 🤖',
    tool_EPIGENETIC_CLOCK: 'એપિજેનેટિક ઘડિયાળ ⏳',
    tool_COMMUNITY: 'કેમ્પસ સમુદાય 👥',
    tool_LEADERBOARD: 'લીડરબોર્ડ 🏆',
    tool_STUDY_ROOMS: 'અભ્યાસ રૂમ 🎧',
    tool_STUDY_SWARM: 'અભ્યાસ ટોળું 🤖',
    tool_QUIZ_BATTLE: 'ક્વિઝ અખાડો ⚔️',
    tool_HACKATHON_RADAR: 'હેકાથોન રડાર 🏆',
    tool_HACKATHON_WAR_ROOM: 'વોર રૂમ ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'જ્ઞાન ઓલિમ્પિયાડ 🏆',
    tool_FACULTY_ADVISORY: 'શિક્ષક સલાહ 🎓',
    tool_ALUMNI_RADAR: 'ભૂતપૂર્વ વિદ્યાર્થી માર્ગદર્શકો 🌐',
    tool_TUTOR_BOUNTY: 'ટ્યુટર બાઉન્ટી 💰',
    tool_STUDY_GUILD_DAO: 'ગિલ્ડ DAO 🏛️',
    tool_CAMPUS_EXCHANGE: 'કેમ્પસ એક્સચેન્જ 📦',
    tool_NOTES_MARKETPLACE: 'નોટ્સ બજાર 🛍️',
    tool_HOSTEL_NUTRITION: 'હોસ્ટેલ મેસ 🥗',
    tool_CAMPUS_TRANSIT: 'કેમ્પસ પરિવહન 🚌',
    tool_CAMPUS_PRINTING: 'કેમ્પસ પ્રિન્ટિંગ 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'ડિજિટલ ટ્વિન 🗺️',
    tool_VIRTUAL_CAMPUS: '2D કેમ્પસ 🏰',
    tool_DEADLINES: 'ડેડલાઇન અને ચેતવણીઓ 🚨',
    tool_FOCUS_GARDEN: 'ફોકસ ગાર્ડન 🌲',
    tool_CIRCADIAN_FOCUS: 'સર્કેડિયન રિધમ ⚡',
    tool_NEURAL_FLOW: 'ન્યુરલ ફ્લો 🧠',
    tool_MENTAL_RESILIENCE: 'માનસિક સુખાકારી 🧘',
    tool_ERGONOMIC_WELLNESS: 'શારીરિક મુદ્રા અને સ્વાસ્થ્ય 👁️',
    tool_CARBON_MARKET: 'કાર્બન માર્કેટ 🌱',

    // View Components
    phase_badge: 'તબક્કો 53 • કેમ્પસ રિસોર્સ બજાર',
    verified_registry: 'ચકાસાયેલ વિદ્યાર્થી રજિસ્ટ્રી ✅',
    campus_exchange_title: 'સ્માર્ટ કેમ્પસ ખોવાયેલ-મળેલ',
    campus_exchange_title_accent: 'અને સાધન વિનિમય 🎒',
    campus_exchange_desc: 'ખોવાયેલી વસ્તુઓની જાણ કરો, મળેલા આઈડી મેળવો અને મિત્રો પાસેથી સાધનો ઉધાર લો.',
    report_share_btn: '+ વસ્તુ નોંધાવો / શેર કરો',
    filter_all: 'બધું',
    filter_lost: 'ખોવાયેલ (LOST)',
    filter_found: 'મળેલ (FOUND)',
    filter_borrow: 'ઉધાર / ભાડે',
    search_items_placeholder: 'વસ્તુ અથવા સ્થળ શોધો...',
    badge_lost: 'ખોવાયેલી વસ્તુ 🔍',
    badge_found: 'મળેલી વસ્તુ 🎁',
    badge_borrow: 'ઉધાર / શેરિંગ 🤝',
    mark_resolved: 'ઉકેલાયેલ તરીકે ચિહ્નિત કરો',
    mark_borrowed: 'ઉધાર આપેલ',
    status_resolved: 'RESOLVED',
    status_claimed: 'CLAIMED',
    report_modal_title: 'ખોવાયેલી / મળેલી વસ્તુની જાણ કરો 🎒',
    field_type: 'પ્રકાર',
    field_category: 'શ્રેણી',
    field_title: 'વસ્તુનું નામ',
    field_location: 'સ્થળની વિગતો',
    field_desc: 'વર્ણન અને ઓળખ',
    field_contact: 'સંપર્ક માહિતી',
    btn_cancel: 'રદ કરો',
    btn_publish: 'પ્રકાશિત કરો',
    opt_lost: 'ખોવાયેલી વસ્તુ',
    opt_found: 'મળેલી વસ્તુ',
    opt_borrow: 'ઉધાર માટે ઉપલબ્ધ',
    opt_calculator: 'સાયન્ટિફિક કેલ્ક્યુલેટર',
    opt_id_card: 'આઈડી કાર્ડ / દસ્તાવેજ',
    opt_lab_equipment: 'લેબ સાધનો / ટૂલ્સ',
    opt_book_notes: 'નોટ્સ / પુસ્તકો',
    opt_electronics: 'ઇલેક્ટ્રોનિક્સ / કેબલ્સ'
  },

  pa: {
    app_subtitle: 'ਪੜ੍ਹਾਈ, ਇਮਤਿਹਾਨਾਂ ਅਤੇ ਕਰੀਅਰ ਲਈ ਸੰਪੂਰਨ ਓਪਰੇਟਿੰਗ ਸਿਸਟਮ',
    cockpit: 'ਕਾਕਪਿਟ 🚀',
    academics: 'ਅਕਾਦਮਿਕ 📚',
    academics_full: 'ਅਕਾਦਮਿਕ ਅਤੇ ਪ੍ਰੀਖਿਆਵਾਂ',
    ai_copilot: 'AI ਕੋ-ਪਾਇਲਟ 🤖',
    ai_copilot_full: 'AI ਸਟੱਡੀ ਟੂਲਜ਼',
    career: 'ਕਰੀਅਰ ਅਤੇ ਮੌਕੇ 💼',
    career_full: 'ਕਰੀਅਰ ਅਤੇ ਇੰਟਰਨਸ਼ਿਪ',
    labs: 'ਖੋਜ ਅਤੇ ਲੈਬਜ਼ 🔬',
    labs_full: 'ਡੀਪਟੈਕ ਅਤੇ ਵਿਗਿਆਨ ਲੈਬਾਂ',
    community: 'ਕੈਂਪਸ ਹੱਬ 👥',
    community_full: 'ਕਮਿਊਨਿਟੀ ਅਤੇ ਅਖਾੜਾ',
    campus: 'ਕੈਂਪਸ ਅਤੇ ਸਿਹਤ 🏫',
    campus_full: 'ਕੈਂਪਸ ਜੀਵਨ ਅਤੇ ਤੰਦਰੁਸਤੀ',
    grandmaster: 'ਗ੍ਰੈਂਡਮਾਸਟਰ 👑',
    roadmap: 'ਰੋਡਮੈਪ 🗺️',
    search: 'ਖੋਜੋ',
    api_online: 'ਆਨਲਾਈਨ ✅',
    api_standby: 'ਸਟੈਂਡਬਾਏ',
    daily_digest: 'ਰੋਜ਼ਾਨਾ ਡਾਇਜੈਸਟ ☀️',
    sign_in: 'ਸਾਈਨ ਇਨ / ਲੌਗਇਨ',
    sign_out: 'ਲੌਗ ਆਉਟ',
    level_scholar: 'ਲੈਵਲ {level} ਵਿਦਵਾਨ 🎓',
    total_xp: 'ਕੁੱਲ XP',
    xp_needed: 'ਅਗਲੇ ਲੈਵਲ ਲਈ XP',
    day_streak: 'ਦਿਨਾਂ ਦੀ ਲੜੀ 🔥',
    edit_profile: 'ਪ੍ਰੋਫਾਈਲ ਬਦਲੋ',
    daily_study_target: 'ਰੋਜ਼ਾਨਾ ਪੜ੍ਹਾਈ ਦਾ ਟੀਚਾ ⏱️',
    target_exams: 'ਟੀਚਾ ਪ੍ਰੀਖਿਆਵਾਂ 🎯',
    dream_career: 'ਸੁਪਨਿਆਂ ਦਾ ਕਰੀਅਰ 💼',
    skills: 'ਹੁਨਰ',
    smart_focus_engine: 'ਸਮਾਰਟ ਫੋਕਸ ਇੰਜਨ ⏱️',
    pomodoro_protocol: 'ਪੋਮੋਡੋਰੋ ਡੂੰਘੀ ਪੜ੍ਹਾਈ ਪ੍ਰੋਟੋਕੋਲ',
    focus_25: '25 ਮਿੰਟ ਧਿਆਨ',
    focus_50: '50 ਮਿੰਟ ਡੂੰਘੀ ਪੜ੍ਹਾਈ',
    break_5: '5 ਮਿੰਟ ਆਰਾਮ',
    study_commitment: 'ਅੱਜ ਦਾ ਅਧਿਐਨ ਸੰਕਲਪ',
    daily_telemetry: 'ਰੋਜ਼ਾਨਾ ਟੀਚਾ ਟਰੈਕਰ',
    time_studied_today: 'ਅੱਜ ਪੜ੍ਹਿਆ ਗਿਆ ਸਮਾਂ:',
    target_label: 'ਟੀਚਾ:',
    remaining_label: 'ਬਾਕੀ ਸਮਾਂ:',
    target_exam_countdowns: 'ਪ੍ਰੀਖਿਆ ਕਾਊਂਟਡਾਊਨ ⏳',
    milestone_tracker: 'ਆਉਣ ਵਾਲੀਆਂ ਪ੍ਰੀਖਿਆਵਾਂ ਦੀ ਸਮਾਂ-ਸਾਰਣੀ',
    view_prep_hub: 'ਤਿਆਰੀ ਕੇਂਦਰ ਦੇਖੋ',
    days_left: 'ਦਿਨ ਬਾਕੀ',
    spaced_repetition_queue: 'ਦੁਹਰਾਈ ਕਤਾਰ (SM-2) 🧠',
    memory_curve: 'ਮੈਮੋਰੀ ਗ੍ਰਾਫ',
    start_rapid_review: 'ਦੁਹਰਾਈ ਸ਼ੁਰੂ ਕਰੋ ⚡',
    due_today: 'ਕਾਰਡ ਅੱਜ ਦੁਹਰਾਉਣ ਲਈ ਹਨ',
    estimated_time: 'ਅੰਦਾਜ਼ਨ ਸਮਾਂ',
    ai_shortcuts_title: 'AI ਸਟੱਡੀ ਸ਼ਾਰਟਕੱਟ 🤖✨',
    ai_shortcuts_sub: 'ਤੁਰੰਤ AI ਟੂਲਜ਼',
    summarize_notes: 'ਨੋਟਸ ਦਾ ਸਾਰ ਬਣਾਓ',
    generate_flashcards: 'ਫਲੈਸ਼ਕਾਰਡ ਬਣਾਓ',
    ask_ai_mentor: 'AI ਮੈਂਟਰ ਨੂੰ ਪੁੱਛੋ',
    quote_text: '"ਲਗਾਤਾਰ ਮਿਹਨਤ ਅਤੇ ਅਨੁਸ਼ਾਸਨ ਹੀ ਵੱਡੀ ਸਫਲਤਾ ਦਿਵਾਉਂਦੇ ਹਨ।"',
    quote_author: '— ਪ੍ਰੇਰਨਾਦਾਇਕ ਵਿਚਾਰ',
    live_telemetry: 'ਲਾਈਵ ਟੈਲੀਮੈਟਰੀ 📡',
    streaming: 'ਸਟ੍ਰੀਮਿੰਗ 🟢',
    paused: 'ਰੋਕਿਆ ਗਿਆ ⏸️',
    footer_text: 'StudentLife OS 16.0 (ਗ੍ਰੈਂਡਮਾਸਟਰ ਸੰਸਕਰਣ) • 100/100 ਪੜਾਅ ਪੂਰੀ ਤਰ੍ਹਾਂ ਸਰਗਰਮ 🏆💯',

    // Tools
    tool_PLANNER: 'ਸਟੱਡੀ ਪਲਾਨਰ 📅',
    tool_SYLLABUS: 'ਸਿਲੇਬਸ ਟਰੈਕਰ 🌲',
    tool_NOTES: 'ਨੋਟਸ ਹੱਬ 📝',
    tool_REVISION: 'ਰਿਵੀਜ਼ਨ ਇੰਜਣ 🧠',
    tool_EXAM_PREP: 'ਪ੍ਰੀਖਿਆ ਤਿਆਰੀ 🎯',
    tool_QUESTION_BANK: 'ਪ੍ਰਸ਼ਨ ਬੈਂਕ 📚',
    tool_MOCK_TEST: 'ਮੌਕ ਟੈਸਟ ⏱️',
    tool_CUSTOM_PAPER: 'ਪੇਪਰ ਜਨਰੇਟਰ 📜',
    tool_RANK_PREDICTOR: 'ਰੈਂਕ ਪ੍ਰੀਡਿਕਟਰ 🎯',
    tool_EXAM_TREND: 'ਕੱਟਆਫ ਰੁਝਾਨ 🔮',
    tool_ANKI_FSRS: 'ਅੰਕੀ FSRS ਸਿੰਕ 🔄',
    tool_ACADEMIC_INTEGRITY: 'ਅਕਾਦਮਿਕ ਸੁਰੱਖਿਆ 🛡️',
    tool_ANALYTICS: 'ਵਿਸ਼ਲੇਸ਼ਣ 📈',
    tool_AI_STUDY: 'AI ਸਟੱਡੀ ਸਹਾਇਕ 🤖',
    tool_AI_MENTOR: 'AI ਮੈਂਟਰ 🎓',
    tool_VOICE_TUTOR: 'ਆਵਾਜ਼ ਅਧਿਆਪਕ 🎙️',
    tool_AI_PODCAST: 'AI ਪੌਡਕਾਸਟ 🎙️',
    tool_SOCRATIC_DEBATE: 'ਬਹਿਸ ਅਖਾੜਾ ⚖️',
    tool_CONCEPT_GRAPH: 'ਕਨਸੈਪਟ ਗ੍ਰਾਫ 🕸️',
    tool_AI_WHITEBOARD: 'AI ਵ੍ਹਾਈਟਬੋਰਡ 🎨',
    tool_DOCUMENT_ANNOTATOR: 'ਪੀਡੀਐਫ ਐਨੋਟੇਟਰ 📝',
    tool_OCR_SCANNER: 'ਓਸੀਆਰ ਸਕੈਨਰ 📷',
    tool_VIDEO_NAVIGATOR: 'ਵੀਡੀਓ ਨੈਵੀਗੇਟਰ 🎬',
    tool_SPEED_READER: 'ਸਪੀਡ ਰੀਡਰ ⚡',
    tool_POLYGLOT_TRANSLATOR: 'ਅਨੁਵਾਦਕ 🌐',
    tool_SLIDE_GENERATOR: 'ਸਲਾਈਡ ਸਟੂਡੀਓ 📊',
    tool_CAREER: 'ਕਰੀਅਰ ਮਾਰਗਦਰਸ਼ਨ 💼',
    tool_RESUME: 'ਰੈਜ਼ਿਊਮੇ ਬਿਲਡਰ 📄',
    tool_INTERNSHIPS: 'ਇੰਟਰਨਸ਼ਿਪ 🎯',
    tool_SCHOLARSHIPS: 'ਵਜ਼ੀਫ਼ਾ ਖੋਜਕ 🏆',
    tool_MOCK_INTERVIEW: 'ਮੌਕ ਇੰਟਰਵਿਊ 🎙️',
    tool_STUDENT_FINANCES: 'ਵਿੱਤ ਅਤੇ ਬਜਟ 💳',
    tool_MICRO_INTERNSHIP: 'ਮਾਈਕ੍ਰੋ-ਗਿਗਸ 💼',
    tool_CAMPUS_INCUBATOR: 'ਸਟਾਰਟਅੱਪ ਇਨਕਿਊਬੇਟਰ 🚀',
    tool_FELLOWSHIP_DRAFTER: 'ਫੈਲੋਸ਼ਿਪ ਡਰਾਫਟਰ 🏅',
    tool_SKILL_PASSPORT: 'ਹੁਨਰ ਪਾਸਪੋਰਟ 🎖️',
    tool_VENTURE_SAFE: 'ਵੈਂਚਰ ਸੇਫ 💼',
    tool_HFT_ORDERBOOK: 'ਆਰਡਰ ਬੁੱਕ 📈',
    tool_RESEARCH_LAB: 'ਖੋਜ ਲੈਬ 🧬',
    tool_ARXIV_SCHOLAR: 'ਆਰਕਾਈਵ ਸਕਾਲਰ 📄',
    tool_CODE_SANDBOX: 'ਕੋਡ ਸੈਂਡਬਾਕਸ 💻',
    tool_LATEX_STUDIO: 'ਲੇਟੈਕਸ ਸਟੂਡੀਓ 📐',
    tool_PATENT_DRAFTER: 'ਪੇਟੈਂਟ ਅਤੇ ਆਈਪੀ 📜',
    tool_HOLO_SIMULATIONS: '3D ਹੋਲੋ ਲੈਬ 🧬',
    tool_QUANTUM_LAB: 'ਕੁਆਂਟਮ ਲੈਬ ⚛️',
    tool_QUANTUM_QKD: 'ਕੁਆਂਟਮ QKD 🔑',
    tool_LAB_NOTEBOOK: 'ਲੈਬ ਨੋਟਬੁੱਕ 🧪',
    tool_KERNEL_PROFILER: 'ਕਰਨਲ ਪ੍ਰੋਫਾਈਲਰ ⚡',
    tool_ASTRODYNAMICS: 'ਖਗੋਲ ਵਿਗਿਆਨ 🪐',
    tool_CHEMICAL_RETRO: 'ਰਸਾਇਣਕ ਸੰਸਲੇਸ਼ਣ 🧪',
    tool_SCHOLAR_TRACKER: 'ਸਕਾਲਰ ਟਰੈਕਰ 🎓',
    tool_NEUROMORPHIC_SNN: 'ਨਿਊਰੋਮੋਰਫਿਕ SNN 🧠',
    tool_PAPER_REFEREE: 'ਸਮੀਖਿਅਕ 📝',
    tool_CRISPR_EDITOR: 'ਜੀਨ ਸੰਪਾਦਕ 🧬',
    tool_FUSION_TOKAMAK: 'ਫਿਊਜ਼ਨ ਟੋਕਾਮਾਕ ⚛️',
    tool_BCI_SPELLER: 'ਬੀਸੀਆਈ ਸਪੈਲਰ 🧠',
    tool_LEGAL_ANALYZER: 'ਕਾਨੂੰਨੀ ਵਿਸ਼ਲੇਸ਼ਕ ⚖️',
    tool_EXOPLANET_PHOTOMETRY: 'ਗ੍ਰਹਿ ਖੋਜ 🔭',
    tool_GRAVITATIONAL_WAVES: 'ਗਰੈਵੀਟੇਸ਼ਨਲ ਤਰੰਗਾਂ 🌌',
    tool_ROBOTICS_KINEMATICS: 'ਰੋਬੋਟਿਕਸ 🤖',
    tool_EPIGENETIC_CLOCK: 'ਐਪੀਜੇਨੇਟਿਕ ਘੜੀ ⏳',
    tool_COMMUNITY: 'ਕੈਂਪਸ ਭਾਈਚਾਰਾ 👥',
    tool_LEADERBOARD: 'ਲੀਡਰਬੋਰਡ 🏆',
    tool_STUDY_ROOMS: 'ਸਟੱਡੀ ਰੂਮ 🎧',
    tool_STUDY_SWARM: 'ਅਧਿਐਨ ਝੁੰਡ 🤖',
    tool_QUIZ_BATTLE: 'ਕਵਿਜ਼ ਅਖਾੜਾ ⚔️',
    tool_HACKATHON_RADAR: 'ਹੈਕਾਥੌਨ ਰਾਡਾਰ 🏆',
    tool_HACKATHON_WAR_ROOM: 'ਵਾਰ ਰੂਮ ⚔️',
    tool_KNOWLEDGE_OLYMPIAD: 'ਗਿਆਨ ਓਲੰਪੀਆਡ 🏆',
    tool_FACULTY_ADVISORY: 'ਫੈਕਲਟੀ ਸਲਾਹ 🎓',
    tool_ALUMNI_RADAR: 'ਸਾਬਕਾ ਵਿਦਿਆਰਥੀ ਮੈਂਟਰਜ਼ 🌐',
    tool_TUTOR_BOUNTY: 'ਟਿਊਟਰ ਬਾਊਂਟੀ 💰',
    tool_STUDY_GUILD_DAO: 'ਗਿਲਡ DAO 🏛️',
    tool_CAMPUS_EXCHANGE: 'ਕੈਂਪਸ ਐਕਸਚੇਂਜ 📦',
    tool_NOTES_MARKETPLACE: 'ਨੋਟਸ ਬਾਜ਼ਾਰ 🛍️',
    tool_HOSTEL_NUTRITION: 'ਹੋਸਟਲ ਮੈੱਸ 🥗',
    tool_CAMPUS_TRANSIT: 'ਕੈਂਪਸ ਆਵਾਜਾਈ 🚌',
    tool_CAMPUS_PRINTING: 'ਕੈਂਪਸ ਪ੍ਰਿੰਟਿੰਗ 🖨️',
    tool_CAMPUS_DIGITAL_TWIN: 'ਡਿਜੀਟਲ ਟਵਿਨ 🗺️',
    tool_VIRTUAL_CAMPUS: '2D ਕੈਂਪਸ 🏰',
    tool_DEADLINES: 'ਅੰਤਮ ਮਿਤੀਆਂ ਅਤੇ ਚੇਤਾਵਨੀਆਂ 🚨',
    tool_FOCUS_GARDEN: 'ਫੋਕਸ ਗਾਰਡਨ 🌲',
    tool_CIRCADIAN_FOCUS: 'ਸਰਕੇਡੀਅਨ ਰਿਦਮ ⚡',
    tool_NEURAL_FLOW: 'ਨਿਊਰਲ ਫਲੋ 🧠',
    tool_MENTAL_RESILIENCE: 'ਮਾਨਸਿਕ ਤੰਦਰੁਸਤੀ 🧘',
    tool_ERGONOMIC_WELLNESS: 'ਸਰੀਰਕ ਮੁਦਰਾ ਸਿਹਤ 👁️',
    tool_CARBON_MARKET: 'ਕਾਰਬਨ ਮਾਰਕੀਟ 🌱',

    // View Components
    phase_badge: 'ਪੜਾਅ 53 • ਕੈਂਪਸ ਸਰੋਤ ਬਾਜ਼ਾਰ',
    verified_registry: 'ਪ੍ਰਮਾਣਿਤ ਵਿਦਿਆਰਥੀ ਰਜਿਸਟਰੀ ✅',
    campus_exchange_title: 'ਸਮਾਰਟ ਕੈਂਪਸ ਗੁਆਚਿਆ-ਮਿਲਿਆ',
    campus_exchange_title_accent: 'ਅਤੇ ਸਮਾਨ ਵਟਾਂਦਰਾ 🎒',
    campus_exchange_desc: 'ਗੁਆਚੀਆਂ ਚੀਜ਼ਾਂ ਦੀ ਰਿਪੋਰਟ ਕਰੋ, ਮਿਲੇ ਆਈਡੀ ਕਾਰਡ ਪ੍ਰਾਪਤ ਕਰੋ ਅਤੇ ਸਾਥੀਆਂ ਤੋਂ ਲੈਬ ਉਪਕਰਣ ਉਧਾਰ ਲਓ।',
    report_share_btn: '+ ਚੀਜ਼ ਰਿਪੋਰਟ / ਸਾਂਝੀ ਕਰੋ',
    filter_all: 'ਸਭ ਕੁਝ',
    filter_lost: 'ਗੁਆਚਿਆ (LOST)',
    filter_found: 'ਮਿਲਿਆ (FOUND)',
    filter_borrow: 'ਉਧਾਰ / ਕਿਰਾਏ ਲਈ',
    search_items_placeholder: 'ਸਮਾਨ ਜਾਂ ਸਥਾਨ ਖੋਜੋ...',
    badge_lost: 'ਗੁਆਚੀ ਚੀਜ਼ 🔍',
    badge_found: 'ਮਿਲੀ ਚੀਜ਼ 🎁',
    badge_borrow: 'ਉਧਾਰ / ਸਾਂਝਾ 🤝',
    mark_resolved: 'ਹੱਲ ਹੋ ਗਿਆ ਮਾਰਕ ਕਰੋ',
    mark_borrowed: 'ਉਧਾਰ ਦਿੱਤਾ ਗਿਆ',
    status_resolved: 'RESOLVED',
    status_claimed: 'CLAIMED',
    report_modal_title: 'ਗੁਆਚੀ / ਮਿਲੀ ਚੀਜ਼ ਰਿਪੋਰਟ ਕਰੋ 🎒',
    field_type: 'ਕਿਸਮ',
    field_category: 'ਸ਼੍ਰੇਣੀ',
    field_title: 'ਚੀਜ਼ ਦਾ ਨਾਮ',
    field_location: 'ਸਥਾਨ ਦਾ ਵੇਰਵਾ',
    field_desc: 'ਵੇਰਵਾ ਅਤੇ ਪਛਾਣ ਚਿੰਨ੍ਹ',
    field_contact: 'ਸੰਪਰਕ ਜਾਣਕਾਰੀ',
    btn_cancel: 'ਰੱਦ ਕਰੋ',
    btn_publish: 'ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ',
    opt_lost: 'ਗੁਆਚੀ ਚੀਜ਼',
    opt_found: 'ਮਿਲੀ ਚੀਜ਼',
    opt_borrow: 'ਉਧਾਰ ਲਈ ਉਪਲਬਧ',
    opt_calculator: 'ਵਿਗਿਆਨਕ ਕੈਲਕੁਲੇਟਰ',
    opt_id_card: 'ਆਈਡੀ ਕਾਰਡ / ਦਸਤਾਵੇਜ਼',
    opt_lab_equipment: 'ਲੈਬ ਉਪਕਰਣ / ਟੂਲਜ਼',
    opt_book_notes: 'ਨੋਟਸ / ਕਿਤਾਬਾਂ',
    opt_electronics: 'ਇਲੈਕਟ੍ਰੋਨਿਕਸ / ਕੇਬਲ'
  },

  // Fallbacks for other regional and global languages automatically inherit English + native terms
  kn: {} as any,
  ml: {} as any,
  or: {} as any,
  ur: {} as any,
  as: {} as any,
  sa: {} as any,
  es: {} as any,
  fr: {} as any,
  de: {} as any,
  ja: {} as any,
  ru: {} as any,
  zh: {} as any,
  ar: {} as any,
};

// Fill fallbacks
const ALL_KEYS = Object.keys(TRANSLATIONS.en);
const ALL_LANGS: SupportedLanguage[] = [
  'en', 'hinglish', 'hi', 'bn', 'te', 'ta', 'mr', 'gu', 'pa',
  'kn', 'ml', 'or', 'ur', 'as', 'sa', 'es', 'fr', 'de', 'ja', 'ru', 'zh', 'ar'
];

ALL_LANGS.forEach((lang) => {
  if (!TRANSLATIONS[lang] || Object.keys(TRANSLATIONS[lang]).length === 0) {
    TRANSLATIONS[lang] = { ...TRANSLATIONS.en };
  } else {
    ALL_KEYS.forEach((key) => {
      if (!TRANSLATIONS[lang][key]) {
        TRANSLATIONS[lang][key] = TRANSLATIONS.en[key];
      }
    });
  }
});

interface LanguageContextType {
  currentLanguage: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  currentLanguage: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<SupportedLanguage>(() => {
    try {
      const saved = localStorage.getItem('studentlife_language') as SupportedLanguage;
      if (saved && TRANSLATIONS[saved]) return saved;
    } catch (e) {}
    return 'hi';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setCurrentLanguageState(lang);
    try {
      localStorage.setItem('studentlife_language', lang);
    } catch (e) {}
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const langDict = TRANSLATIONS[currentLanguage] || TRANSLATIONS.en;
    let text = langDict[key] || TRANSLATIONS.en[key] || key;

    if (params) {
      Object.entries(params).forEach(([pKey, pVal]) => {
        text = text.replace(new RegExp(`\\{${pKey}\\}`, 'g'), String(pVal));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
